// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Grafana.Apps.V0Alpha1
{
    /// <summary>
    /// Manages Grafana Git Sync connections used by repositories for provider authentication.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Grafana = Pulumiverse.Grafana;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Grafana.Apps.V0Alpha1.ProvisioningConnection("example", new()
    ///     {
    ///         Metadata = new Grafana.Apps.V0Alpha1.Inputs.ProvisioningConnectionMetadataArgs
    ///         {
    ///             Uid = "my-github-connection",
    ///         },
    ///         Spec = new Grafana.Apps.V0Alpha1.Inputs.ProvisioningConnectionSpecArgs
    ///         {
    ///             Title = "My GitHub App Connection",
    ///             Description = "GitHub App connection used by a folder-scoped Git Sync repository",
    ///             Type = "github",
    ///             Url = "https://github.com",
    ///             Github = new Grafana.Apps.V0Alpha1.Inputs.ProvisioningConnectionSpecGithubArgs
    ///             {
    ///                 AppId = "12345",
    ///                 InstallationId = "67890",
    ///             },
    ///         },
    ///         Secure = new Grafana.Apps.V0Alpha1.Inputs.ProvisioningConnectionSecureArgs
    ///         {
    ///             PrivateKey = 
    ///             {
    ///                 { "create", "replace-me" },
    ///             },
    ///         },
    ///         SecureVersion = 1,
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [GrafanaResourceType("grafana:apps/v0alpha1/provisioningConnection:ProvisioningConnection")]
    public partial class ProvisioningConnection : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The metadata of the resource.
        /// </summary>
        [Output("metadata")]
        public Output<Outputs.ProvisioningConnectionMetadata?> Metadata { get; private set; } = null!;

        /// <summary>
        /// Options for applying the resource.
        /// </summary>
        [Output("options")]
        public Output<Outputs.ProvisioningConnectionOptions?> Options { get; private set; } = null!;

        /// <summary>
        /// Sensitive credentials. Values are write-only and never stored in Terraform state.
        /// </summary>
        [Output("secure")]
        public Output<Outputs.ProvisioningConnectionSecure?> Secure { get; private set; } = null!;

        /// <summary>
        /// Set this to 1 when using `Secure`, then increment it to trigger re-application of secure values.
        /// </summary>
        [Output("secureVersion")]
        public Output<int?> SecureVersion { get; private set; } = null!;

        /// <summary>
        /// The spec of the resource.
        /// </summary>
        [Output("spec")]
        public Output<Outputs.ProvisioningConnectionSpec?> Spec { get; private set; } = null!;


        /// <summary>
        /// Create a ProvisioningConnection resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ProvisioningConnection(string name, ProvisioningConnectionArgs? args = null, CustomResourceOptions? options = null)
            : base("grafana:apps/v0alpha1/provisioningConnection:ProvisioningConnection", name, args ?? new ProvisioningConnectionArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ProvisioningConnection(string name, Input<string> id, ProvisioningConnectionState? state = null, CustomResourceOptions? options = null)
            : base("grafana:apps/v0alpha1/provisioningConnection:ProvisioningConnection", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ProvisioningConnection resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ProvisioningConnection Get(string name, Input<string> id, ProvisioningConnectionState? state = null, CustomResourceOptions? options = null)
        {
            return new ProvisioningConnection(name, id, state, options);
        }
    }

    public sealed class ProvisioningConnectionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The metadata of the resource.
        /// </summary>
        [Input("metadata")]
        public Input<Inputs.ProvisioningConnectionMetadataArgs>? Metadata { get; set; }

        /// <summary>
        /// Options for applying the resource.
        /// </summary>
        [Input("options")]
        public Input<Inputs.ProvisioningConnectionOptionsArgs>? Options { get; set; }

        /// <summary>
        /// Sensitive credentials. Values are write-only and never stored in Terraform state.
        /// </summary>
        [Input("secure")]
        public Input<Inputs.ProvisioningConnectionSecureArgs>? Secure { get; set; }

        /// <summary>
        /// Set this to 1 when using `Secure`, then increment it to trigger re-application of secure values.
        /// </summary>
        [Input("secureVersion")]
        public Input<int>? SecureVersion { get; set; }

        /// <summary>
        /// The spec of the resource.
        /// </summary>
        [Input("spec")]
        public Input<Inputs.ProvisioningConnectionSpecArgs>? Spec { get; set; }

        public ProvisioningConnectionArgs()
        {
        }
        public static new ProvisioningConnectionArgs Empty => new ProvisioningConnectionArgs();
    }

    public sealed class ProvisioningConnectionState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The metadata of the resource.
        /// </summary>
        [Input("metadata")]
        public Input<Inputs.ProvisioningConnectionMetadataGetArgs>? Metadata { get; set; }

        /// <summary>
        /// Options for applying the resource.
        /// </summary>
        [Input("options")]
        public Input<Inputs.ProvisioningConnectionOptionsGetArgs>? Options { get; set; }

        /// <summary>
        /// Sensitive credentials. Values are write-only and never stored in Terraform state.
        /// </summary>
        [Input("secure")]
        public Input<Inputs.ProvisioningConnectionSecureGetArgs>? Secure { get; set; }

        /// <summary>
        /// Set this to 1 when using `Secure`, then increment it to trigger re-application of secure values.
        /// </summary>
        [Input("secureVersion")]
        public Input<int>? SecureVersion { get; set; }

        /// <summary>
        /// The spec of the resource.
        /// </summary>
        [Input("spec")]
        public Input<Inputs.ProvisioningConnectionSpecGetArgs>? Spec { get; set; }

        public ProvisioningConnectionState()
        {
        }
        public static new ProvisioningConnectionState Empty => new ProvisioningConnectionState();
    }
}
