template: external-bridged-provider
provider: grafana
organization: pulumiverse
major-version: 1
providerDefaultBranch: main
upstreamProviderOrg: grafana
publishRegistry: false
plugins:
    - name: terraform
      version: "1.0.19"
      kind: converter
    - name: random
      version: "4.16.7"
    - name: aws
      version: "6.56.1"
languages:
    - dotnet
    - go
    - nodejs
    - python
publish:
    sdk: "all,!java"
    cdn: false
license:
    ignore:
        - github.com/apache/arrow/go/v15
        - github.com/grafana/grafana # Is AGPL-3.0, but compatible with MPLv2.0
        - github.com/grafana/grafana-com-public-clients/go/gcom # Temporary while Grafana provider hasn't been upgraded yet
        - github.com/grafana/k6-cloud-openapi-client-go # https://github.com/grafana/k6-cloud-openapi-client-go/issues/7
pulumiConvert: 1
