// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.grafana;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.grafana.inputs.ServiceAccountPermissionPermissionArgs;
import java.lang.Integer;
import java.util.List;
import java.util.Objects;


public final class ServiceAccountPermissionArgs extends com.pulumi.resources.ResourceArgs {

    public static final ServiceAccountPermissionArgs Empty = new ServiceAccountPermissionArgs();

    /**
     * The permission items to add/update. Items that are omitted from the list will be removed.
     * 
     */
    @Import(name="permissions", required=true)
    private Output<List<ServiceAccountPermissionPermissionArgs>> permissions;

    /**
     * @return The permission items to add/update. Items that are omitted from the list will be removed.
     * 
     */
    public Output<List<ServiceAccountPermissionPermissionArgs>> permissions() {
        return this.permissions;
    }

    /**
     * The id of the service account.
     * 
     */
    @Import(name="serviceAccountId", required=true)
    private Output<Integer> serviceAccountId;

    /**
     * @return The id of the service account.
     * 
     */
    public Output<Integer> serviceAccountId() {
        return this.serviceAccountId;
    }

    private ServiceAccountPermissionArgs() {}

    private ServiceAccountPermissionArgs(ServiceAccountPermissionArgs $) {
        this.permissions = $.permissions;
        this.serviceAccountId = $.serviceAccountId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ServiceAccountPermissionArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ServiceAccountPermissionArgs $;

        public Builder() {
            $ = new ServiceAccountPermissionArgs();
        }

        public Builder(ServiceAccountPermissionArgs defaults) {
            $ = new ServiceAccountPermissionArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param permissions The permission items to add/update. Items that are omitted from the list will be removed.
         * 
         * @return builder
         * 
         */
        public Builder permissions(Output<List<ServiceAccountPermissionPermissionArgs>> permissions) {
            $.permissions = permissions;
            return this;
        }

        /**
         * @param permissions The permission items to add/update. Items that are omitted from the list will be removed.
         * 
         * @return builder
         * 
         */
        public Builder permissions(List<ServiceAccountPermissionPermissionArgs> permissions) {
            return permissions(Output.of(permissions));
        }

        /**
         * @param permissions The permission items to add/update. Items that are omitted from the list will be removed.
         * 
         * @return builder
         * 
         */
        public Builder permissions(ServiceAccountPermissionPermissionArgs... permissions) {
            return permissions(List.of(permissions));
        }

        /**
         * @param serviceAccountId The id of the service account.
         * 
         * @return builder
         * 
         */
        public Builder serviceAccountId(Output<Integer> serviceAccountId) {
            $.serviceAccountId = serviceAccountId;
            return this;
        }

        /**
         * @param serviceAccountId The id of the service account.
         * 
         * @return builder
         * 
         */
        public Builder serviceAccountId(Integer serviceAccountId) {
            return serviceAccountId(Output.of(serviceAccountId));
        }

        public ServiceAccountPermissionArgs build() {
            $.permissions = Objects.requireNonNull($.permissions, "expected parameter 'permissions' to be non-null");
            $.serviceAccountId = Objects.requireNonNull($.serviceAccountId, "expected parameter 'serviceAccountId' to be non-null");
            return $;
        }
    }

}
