// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Grafana.Cloud.Inputs
{

    public sealed class GetProviderAwsCloudwatchScrapeJobServiceMetricArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the metric to scrape.
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        [Input("statistics", required: true)]
        private List<string>? _statistics;

        /// <summary>
        /// A set of statistics to scrape.
        /// </summary>
        public List<string> Statistics
        {
            get => _statistics ?? (_statistics = new List<string>());
            set => _statistics = value;
        }

        public GetProviderAwsCloudwatchScrapeJobServiceMetricArgs()
        {
        }
        public static new GetProviderAwsCloudwatchScrapeJobServiceMetricArgs Empty => new GetProviderAwsCloudwatchScrapeJobServiceMetricArgs();
    }
}
