// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Grafana
{
    public static class GetOncallAction
    {
        /// <summary>
        /// **Note:** This data source is going to be deprecated, please use outgoing webhook data source instead.
        /// * [HTTP API](https://grafana.com/docs/grafana-cloud/oncall/oncall-api-reference/outgoing_webhooks/)
        /// </summary>
        public static Task<GetOncallActionResult> InvokeAsync(GetOncallActionArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetOncallActionResult>("grafana:index/getOncallAction:getOncallAction", args ?? new GetOncallActionArgs(), options.WithDefaults());

        /// <summary>
        /// **Note:** This data source is going to be deprecated, please use outgoing webhook data source instead.
        /// * [HTTP API](https://grafana.com/docs/grafana-cloud/oncall/oncall-api-reference/outgoing_webhooks/)
        /// </summary>
        public static Output<GetOncallActionResult> Invoke(GetOncallActionInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetOncallActionResult>("grafana:index/getOncallAction:getOncallAction", args ?? new GetOncallActionInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetOncallActionArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The action name.
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetOncallActionArgs()
        {
        }
        public static new GetOncallActionArgs Empty => new GetOncallActionArgs();
    }

    public sealed class GetOncallActionInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The action name.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetOncallActionInvokeArgs()
        {
        }
        public static new GetOncallActionInvokeArgs Empty => new GetOncallActionInvokeArgs();
    }


    [OutputType]
    public sealed class GetOncallActionResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The action name.
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private GetOncallActionResult(
            string id,

            string name)
        {
            Id = id;
            Name = name;
        }
    }
}
