// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package assistant

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-grafana/sdk/v2/go/grafana/internal"
)

var _ = internal.GetEnvOrDefault

type McpServerConfiguration struct {
	// Built-in provider ID (e.g. cursor). When set, tools are provided locally.
	BuiltinId *string `pulumi:"builtinId"`
	// Tool approval policies keyed by tool name (`autoApprove`, `alwaysAsk`, or empty for default).
	ToolApprovalPolicies map[string]string `pulumi:"toolApprovalPolicies"`
	// Tool preferences keyed by tool name (`enabled` or `disabled`).
	ToolPreferences map[string]string `pulumi:"toolPreferences"`
	// MCP server URL.
	Url *string `pulumi:"url"`
}

// McpServerConfigurationInput is an input type that accepts McpServerConfigurationArgs and McpServerConfigurationOutput values.
// You can construct a concrete instance of `McpServerConfigurationInput` via:
//
//	McpServerConfigurationArgs{...}
type McpServerConfigurationInput interface {
	pulumi.Input

	ToMcpServerConfigurationOutput() McpServerConfigurationOutput
	ToMcpServerConfigurationOutputWithContext(context.Context) McpServerConfigurationOutput
}

type McpServerConfigurationArgs struct {
	// Built-in provider ID (e.g. cursor). When set, tools are provided locally.
	BuiltinId pulumi.StringPtrInput `pulumi:"builtinId"`
	// Tool approval policies keyed by tool name (`autoApprove`, `alwaysAsk`, or empty for default).
	ToolApprovalPolicies pulumi.StringMapInput `pulumi:"toolApprovalPolicies"`
	// Tool preferences keyed by tool name (`enabled` or `disabled`).
	ToolPreferences pulumi.StringMapInput `pulumi:"toolPreferences"`
	// MCP server URL.
	Url pulumi.StringPtrInput `pulumi:"url"`
}

func (McpServerConfigurationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*McpServerConfiguration)(nil)).Elem()
}

func (i McpServerConfigurationArgs) ToMcpServerConfigurationOutput() McpServerConfigurationOutput {
	return i.ToMcpServerConfigurationOutputWithContext(context.Background())
}

func (i McpServerConfigurationArgs) ToMcpServerConfigurationOutputWithContext(ctx context.Context) McpServerConfigurationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(McpServerConfigurationOutput)
}

func (i McpServerConfigurationArgs) ToMcpServerConfigurationPtrOutput() McpServerConfigurationPtrOutput {
	return i.ToMcpServerConfigurationPtrOutputWithContext(context.Background())
}

func (i McpServerConfigurationArgs) ToMcpServerConfigurationPtrOutputWithContext(ctx context.Context) McpServerConfigurationPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(McpServerConfigurationOutput).ToMcpServerConfigurationPtrOutputWithContext(ctx)
}

// McpServerConfigurationPtrInput is an input type that accepts McpServerConfigurationArgs, McpServerConfigurationPtr and McpServerConfigurationPtrOutput values.
// You can construct a concrete instance of `McpServerConfigurationPtrInput` via:
//
//	        McpServerConfigurationArgs{...}
//
//	or:
//
//	        nil
type McpServerConfigurationPtrInput interface {
	pulumi.Input

	ToMcpServerConfigurationPtrOutput() McpServerConfigurationPtrOutput
	ToMcpServerConfigurationPtrOutputWithContext(context.Context) McpServerConfigurationPtrOutput
}

type mcpServerConfigurationPtrType McpServerConfigurationArgs

func McpServerConfigurationPtr(v *McpServerConfigurationArgs) McpServerConfigurationPtrInput {
	return (*mcpServerConfigurationPtrType)(v)
}

func (*mcpServerConfigurationPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**McpServerConfiguration)(nil)).Elem()
}

func (i *mcpServerConfigurationPtrType) ToMcpServerConfigurationPtrOutput() McpServerConfigurationPtrOutput {
	return i.ToMcpServerConfigurationPtrOutputWithContext(context.Background())
}

func (i *mcpServerConfigurationPtrType) ToMcpServerConfigurationPtrOutputWithContext(ctx context.Context) McpServerConfigurationPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(McpServerConfigurationPtrOutput)
}

type McpServerConfigurationOutput struct{ *pulumi.OutputState }

func (McpServerConfigurationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*McpServerConfiguration)(nil)).Elem()
}

func (o McpServerConfigurationOutput) ToMcpServerConfigurationOutput() McpServerConfigurationOutput {
	return o
}

func (o McpServerConfigurationOutput) ToMcpServerConfigurationOutputWithContext(ctx context.Context) McpServerConfigurationOutput {
	return o
}

func (o McpServerConfigurationOutput) ToMcpServerConfigurationPtrOutput() McpServerConfigurationPtrOutput {
	return o.ToMcpServerConfigurationPtrOutputWithContext(context.Background())
}

func (o McpServerConfigurationOutput) ToMcpServerConfigurationPtrOutputWithContext(ctx context.Context) McpServerConfigurationPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v McpServerConfiguration) *McpServerConfiguration {
		return &v
	}).(McpServerConfigurationPtrOutput)
}

// Built-in provider ID (e.g. cursor). When set, tools are provided locally.
func (o McpServerConfigurationOutput) BuiltinId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v McpServerConfiguration) *string { return v.BuiltinId }).(pulumi.StringPtrOutput)
}

// Tool approval policies keyed by tool name (`autoApprove`, `alwaysAsk`, or empty for default).
func (o McpServerConfigurationOutput) ToolApprovalPolicies() pulumi.StringMapOutput {
	return o.ApplyT(func(v McpServerConfiguration) map[string]string { return v.ToolApprovalPolicies }).(pulumi.StringMapOutput)
}

// Tool preferences keyed by tool name (`enabled` or `disabled`).
func (o McpServerConfigurationOutput) ToolPreferences() pulumi.StringMapOutput {
	return o.ApplyT(func(v McpServerConfiguration) map[string]string { return v.ToolPreferences }).(pulumi.StringMapOutput)
}

// MCP server URL.
func (o McpServerConfigurationOutput) Url() pulumi.StringPtrOutput {
	return o.ApplyT(func(v McpServerConfiguration) *string { return v.Url }).(pulumi.StringPtrOutput)
}

type McpServerConfigurationPtrOutput struct{ *pulumi.OutputState }

func (McpServerConfigurationPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**McpServerConfiguration)(nil)).Elem()
}

func (o McpServerConfigurationPtrOutput) ToMcpServerConfigurationPtrOutput() McpServerConfigurationPtrOutput {
	return o
}

func (o McpServerConfigurationPtrOutput) ToMcpServerConfigurationPtrOutputWithContext(ctx context.Context) McpServerConfigurationPtrOutput {
	return o
}

func (o McpServerConfigurationPtrOutput) Elem() McpServerConfigurationOutput {
	return o.ApplyT(func(v *McpServerConfiguration) McpServerConfiguration {
		if v != nil {
			return *v
		}
		var ret McpServerConfiguration
		return ret
	}).(McpServerConfigurationOutput)
}

// Built-in provider ID (e.g. cursor). When set, tools are provided locally.
func (o McpServerConfigurationPtrOutput) BuiltinId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *McpServerConfiguration) *string {
		if v == nil {
			return nil
		}
		return v.BuiltinId
	}).(pulumi.StringPtrOutput)
}

// Tool approval policies keyed by tool name (`autoApprove`, `alwaysAsk`, or empty for default).
func (o McpServerConfigurationPtrOutput) ToolApprovalPolicies() pulumi.StringMapOutput {
	return o.ApplyT(func(v *McpServerConfiguration) map[string]string {
		if v == nil {
			return nil
		}
		return v.ToolApprovalPolicies
	}).(pulumi.StringMapOutput)
}

// Tool preferences keyed by tool name (`enabled` or `disabled`).
func (o McpServerConfigurationPtrOutput) ToolPreferences() pulumi.StringMapOutput {
	return o.ApplyT(func(v *McpServerConfiguration) map[string]string {
		if v == nil {
			return nil
		}
		return v.ToolPreferences
	}).(pulumi.StringMapOutput)
}

// MCP server URL.
func (o McpServerConfigurationPtrOutput) Url() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *McpServerConfiguration) *string {
		if v == nil {
			return nil
		}
		return v.Url
	}).(pulumi.StringPtrOutput)
}

type SkillAllowedTool struct {
	// Integration UUID.
	IntegrationId string `pulumi:"integrationId"`
	// MCP tool name.
	ToolName string `pulumi:"toolName"`
}

// SkillAllowedToolInput is an input type that accepts SkillAllowedToolArgs and SkillAllowedToolOutput values.
// You can construct a concrete instance of `SkillAllowedToolInput` via:
//
//	SkillAllowedToolArgs{...}
type SkillAllowedToolInput interface {
	pulumi.Input

	ToSkillAllowedToolOutput() SkillAllowedToolOutput
	ToSkillAllowedToolOutputWithContext(context.Context) SkillAllowedToolOutput
}

type SkillAllowedToolArgs struct {
	// Integration UUID.
	IntegrationId pulumi.StringInput `pulumi:"integrationId"`
	// MCP tool name.
	ToolName pulumi.StringInput `pulumi:"toolName"`
}

func (SkillAllowedToolArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SkillAllowedTool)(nil)).Elem()
}

func (i SkillAllowedToolArgs) ToSkillAllowedToolOutput() SkillAllowedToolOutput {
	return i.ToSkillAllowedToolOutputWithContext(context.Background())
}

func (i SkillAllowedToolArgs) ToSkillAllowedToolOutputWithContext(ctx context.Context) SkillAllowedToolOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SkillAllowedToolOutput)
}

// SkillAllowedToolArrayInput is an input type that accepts SkillAllowedToolArray and SkillAllowedToolArrayOutput values.
// You can construct a concrete instance of `SkillAllowedToolArrayInput` via:
//
//	SkillAllowedToolArray{ SkillAllowedToolArgs{...} }
type SkillAllowedToolArrayInput interface {
	pulumi.Input

	ToSkillAllowedToolArrayOutput() SkillAllowedToolArrayOutput
	ToSkillAllowedToolArrayOutputWithContext(context.Context) SkillAllowedToolArrayOutput
}

type SkillAllowedToolArray []SkillAllowedToolInput

func (SkillAllowedToolArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]SkillAllowedTool)(nil)).Elem()
}

func (i SkillAllowedToolArray) ToSkillAllowedToolArrayOutput() SkillAllowedToolArrayOutput {
	return i.ToSkillAllowedToolArrayOutputWithContext(context.Background())
}

func (i SkillAllowedToolArray) ToSkillAllowedToolArrayOutputWithContext(ctx context.Context) SkillAllowedToolArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SkillAllowedToolArrayOutput)
}

type SkillAllowedToolOutput struct{ *pulumi.OutputState }

func (SkillAllowedToolOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SkillAllowedTool)(nil)).Elem()
}

func (o SkillAllowedToolOutput) ToSkillAllowedToolOutput() SkillAllowedToolOutput {
	return o
}

func (o SkillAllowedToolOutput) ToSkillAllowedToolOutputWithContext(ctx context.Context) SkillAllowedToolOutput {
	return o
}

// Integration UUID.
func (o SkillAllowedToolOutput) IntegrationId() pulumi.StringOutput {
	return o.ApplyT(func(v SkillAllowedTool) string { return v.IntegrationId }).(pulumi.StringOutput)
}

// MCP tool name.
func (o SkillAllowedToolOutput) ToolName() pulumi.StringOutput {
	return o.ApplyT(func(v SkillAllowedTool) string { return v.ToolName }).(pulumi.StringOutput)
}

type SkillAllowedToolArrayOutput struct{ *pulumi.OutputState }

func (SkillAllowedToolArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]SkillAllowedTool)(nil)).Elem()
}

func (o SkillAllowedToolArrayOutput) ToSkillAllowedToolArrayOutput() SkillAllowedToolArrayOutput {
	return o
}

func (o SkillAllowedToolArrayOutput) ToSkillAllowedToolArrayOutputWithContext(ctx context.Context) SkillAllowedToolArrayOutput {
	return o
}

func (o SkillAllowedToolArrayOutput) Index(i pulumi.IntInput) SkillAllowedToolOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) SkillAllowedTool {
		return vs[0].([]SkillAllowedTool)[vs[1].(int)]
	}).(SkillAllowedToolOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*McpServerConfigurationInput)(nil)).Elem(), McpServerConfigurationArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*McpServerConfigurationPtrInput)(nil)).Elem(), McpServerConfigurationArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*SkillAllowedToolInput)(nil)).Elem(), SkillAllowedToolArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*SkillAllowedToolArrayInput)(nil)).Elem(), SkillAllowedToolArray{})
	pulumi.RegisterOutputType(McpServerConfigurationOutput{})
	pulumi.RegisterOutputType(McpServerConfigurationPtrOutput{})
	pulumi.RegisterOutputType(SkillAllowedToolOutput{})
	pulumi.RegisterOutputType(SkillAllowedToolArrayOutput{})
}
