// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.grafana.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.grafana.outputs.SLOAlertingSlowburnAnnotation;
import com.pulumi.grafana.outputs.SLOAlertingSlowburnLabel;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class SLOAlertingSlowburn {
    private @Nullable List<SLOAlertingSlowburnAnnotation> annotations;
    /**
     * @return Additional labels that will be attached to all metrics generated from the query. These labels are useful for grouping SLOs in dashboard views that you create by hand.
     * 
     */
    private @Nullable List<SLOAlertingSlowburnLabel> labels;

    private SLOAlertingSlowburn() {}
    public List<SLOAlertingSlowburnAnnotation> annotations() {
        return this.annotations == null ? List.of() : this.annotations;
    }
    /**
     * @return Additional labels that will be attached to all metrics generated from the query. These labels are useful for grouping SLOs in dashboard views that you create by hand.
     * 
     */
    public List<SLOAlertingSlowburnLabel> labels() {
        return this.labels == null ? List.of() : this.labels;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SLOAlertingSlowburn defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<SLOAlertingSlowburnAnnotation> annotations;
        private @Nullable List<SLOAlertingSlowburnLabel> labels;
        public Builder() {}
        public Builder(SLOAlertingSlowburn defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.annotations = defaults.annotations;
    	      this.labels = defaults.labels;
        }

        @CustomType.Setter
        public Builder annotations(@Nullable List<SLOAlertingSlowburnAnnotation> annotations) {
            this.annotations = annotations;
            return this;
        }
        public Builder annotations(SLOAlertingSlowburnAnnotation... annotations) {
            return annotations(List.of(annotations));
        }
        @CustomType.Setter
        public Builder labels(@Nullable List<SLOAlertingSlowburnLabel> labels) {
            this.labels = labels;
            return this;
        }
        public Builder labels(SLOAlertingSlowburnLabel... labels) {
            return labels(List.of(labels));
        }
        public SLOAlertingSlowburn build() {
            final var o = new SLOAlertingSlowburn();
            o.annotations = annotations;
            o.labels = labels;
            return o;
        }
    }
}
