// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package frontendobservability

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-grafana/sdk/go/grafana/internal"
)

// ## Example Usage
//
// ## Import
//
// ```sh
// $ pulumi import grafana:frontendObservability/app:App name "{{ stack_id }}:{{ name }}"
// ```
type App struct {
	pulumi.CustomResourceState

	// A list of allowed origins for CORS.
	AllowedOrigins pulumi.StringArrayOutput `pulumi:"allowedOrigins"`
	// The collector URL Grafana Cloud Frontend Observability. Use this endpoint to send your Telemetry.
	CollectorEndpoint pulumi.StringOutput `pulumi:"collectorEndpoint"`
	// The extra attributes to append in each signal.
	ExtraLogAttributes pulumi.StringMapOutput `pulumi:"extraLogAttributes"`
	Name               pulumi.StringOutput    `pulumi:"name"`
	// The key-value settings of the Frontend Observability app. Available Settings: `{combineLabData=(0|1)}`
	Settings pulumi.StringMapOutput `pulumi:"settings"`
	StackId  pulumi.IntOutput       `pulumi:"stackId"`
}

// NewApp registers a new resource with the given unique name, arguments, and options.
func NewApp(ctx *pulumi.Context,
	name string, args *AppArgs, opts ...pulumi.ResourceOption) (*App, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.AllowedOrigins == nil {
		return nil, errors.New("invalid value for required argument 'AllowedOrigins'")
	}
	if args.ExtraLogAttributes == nil {
		return nil, errors.New("invalid value for required argument 'ExtraLogAttributes'")
	}
	if args.Settings == nil {
		return nil, errors.New("invalid value for required argument 'Settings'")
	}
	if args.StackId == nil {
		return nil, errors.New("invalid value for required argument 'StackId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource App
	err := ctx.RegisterResource("grafana:frontendObservability/app:App", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetApp gets an existing App resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetApp(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AppState, opts ...pulumi.ResourceOption) (*App, error) {
	var resource App
	err := ctx.ReadResource("grafana:frontendObservability/app:App", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering App resources.
type appState struct {
	// A list of allowed origins for CORS.
	AllowedOrigins []string `pulumi:"allowedOrigins"`
	// The collector URL Grafana Cloud Frontend Observability. Use this endpoint to send your Telemetry.
	CollectorEndpoint *string `pulumi:"collectorEndpoint"`
	// The extra attributes to append in each signal.
	ExtraLogAttributes map[string]string `pulumi:"extraLogAttributes"`
	Name               *string           `pulumi:"name"`
	// The key-value settings of the Frontend Observability app. Available Settings: `{combineLabData=(0|1)}`
	Settings map[string]string `pulumi:"settings"`
	StackId  *int              `pulumi:"stackId"`
}

type AppState struct {
	// A list of allowed origins for CORS.
	AllowedOrigins pulumi.StringArrayInput
	// The collector URL Grafana Cloud Frontend Observability. Use this endpoint to send your Telemetry.
	CollectorEndpoint pulumi.StringPtrInput
	// The extra attributes to append in each signal.
	ExtraLogAttributes pulumi.StringMapInput
	Name               pulumi.StringPtrInput
	// The key-value settings of the Frontend Observability app. Available Settings: `{combineLabData=(0|1)}`
	Settings pulumi.StringMapInput
	StackId  pulumi.IntPtrInput
}

func (AppState) ElementType() reflect.Type {
	return reflect.TypeOf((*appState)(nil)).Elem()
}

type appArgs struct {
	// A list of allowed origins for CORS.
	AllowedOrigins []string `pulumi:"allowedOrigins"`
	// The extra attributes to append in each signal.
	ExtraLogAttributes map[string]string `pulumi:"extraLogAttributes"`
	Name               *string           `pulumi:"name"`
	// The key-value settings of the Frontend Observability app. Available Settings: `{combineLabData=(0|1)}`
	Settings map[string]string `pulumi:"settings"`
	StackId  int               `pulumi:"stackId"`
}

// The set of arguments for constructing a App resource.
type AppArgs struct {
	// A list of allowed origins for CORS.
	AllowedOrigins pulumi.StringArrayInput
	// The extra attributes to append in each signal.
	ExtraLogAttributes pulumi.StringMapInput
	Name               pulumi.StringPtrInput
	// The key-value settings of the Frontend Observability app. Available Settings: `{combineLabData=(0|1)}`
	Settings pulumi.StringMapInput
	StackId  pulumi.IntInput
}

func (AppArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*appArgs)(nil)).Elem()
}

type AppInput interface {
	pulumi.Input

	ToAppOutput() AppOutput
	ToAppOutputWithContext(ctx context.Context) AppOutput
}

func (*App) ElementType() reflect.Type {
	return reflect.TypeOf((**App)(nil)).Elem()
}

func (i *App) ToAppOutput() AppOutput {
	return i.ToAppOutputWithContext(context.Background())
}

func (i *App) ToAppOutputWithContext(ctx context.Context) AppOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AppOutput)
}

// AppArrayInput is an input type that accepts AppArray and AppArrayOutput values.
// You can construct a concrete instance of `AppArrayInput` via:
//
//	AppArray{ AppArgs{...} }
type AppArrayInput interface {
	pulumi.Input

	ToAppArrayOutput() AppArrayOutput
	ToAppArrayOutputWithContext(context.Context) AppArrayOutput
}

type AppArray []AppInput

func (AppArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*App)(nil)).Elem()
}

func (i AppArray) ToAppArrayOutput() AppArrayOutput {
	return i.ToAppArrayOutputWithContext(context.Background())
}

func (i AppArray) ToAppArrayOutputWithContext(ctx context.Context) AppArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AppArrayOutput)
}

// AppMapInput is an input type that accepts AppMap and AppMapOutput values.
// You can construct a concrete instance of `AppMapInput` via:
//
//	AppMap{ "key": AppArgs{...} }
type AppMapInput interface {
	pulumi.Input

	ToAppMapOutput() AppMapOutput
	ToAppMapOutputWithContext(context.Context) AppMapOutput
}

type AppMap map[string]AppInput

func (AppMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*App)(nil)).Elem()
}

func (i AppMap) ToAppMapOutput() AppMapOutput {
	return i.ToAppMapOutputWithContext(context.Background())
}

func (i AppMap) ToAppMapOutputWithContext(ctx context.Context) AppMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AppMapOutput)
}

type AppOutput struct{ *pulumi.OutputState }

func (AppOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**App)(nil)).Elem()
}

func (o AppOutput) ToAppOutput() AppOutput {
	return o
}

func (o AppOutput) ToAppOutputWithContext(ctx context.Context) AppOutput {
	return o
}

// A list of allowed origins for CORS.
func (o AppOutput) AllowedOrigins() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *App) pulumi.StringArrayOutput { return v.AllowedOrigins }).(pulumi.StringArrayOutput)
}

// The collector URL Grafana Cloud Frontend Observability. Use this endpoint to send your Telemetry.
func (o AppOutput) CollectorEndpoint() pulumi.StringOutput {
	return o.ApplyT(func(v *App) pulumi.StringOutput { return v.CollectorEndpoint }).(pulumi.StringOutput)
}

// The extra attributes to append in each signal.
func (o AppOutput) ExtraLogAttributes() pulumi.StringMapOutput {
	return o.ApplyT(func(v *App) pulumi.StringMapOutput { return v.ExtraLogAttributes }).(pulumi.StringMapOutput)
}

func (o AppOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *App) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The key-value settings of the Frontend Observability app. Available Settings: `{combineLabData=(0|1)}`
func (o AppOutput) Settings() pulumi.StringMapOutput {
	return o.ApplyT(func(v *App) pulumi.StringMapOutput { return v.Settings }).(pulumi.StringMapOutput)
}

func (o AppOutput) StackId() pulumi.IntOutput {
	return o.ApplyT(func(v *App) pulumi.IntOutput { return v.StackId }).(pulumi.IntOutput)
}

type AppArrayOutput struct{ *pulumi.OutputState }

func (AppArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*App)(nil)).Elem()
}

func (o AppArrayOutput) ToAppArrayOutput() AppArrayOutput {
	return o
}

func (o AppArrayOutput) ToAppArrayOutputWithContext(ctx context.Context) AppArrayOutput {
	return o
}

func (o AppArrayOutput) Index(i pulumi.IntInput) AppOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *App {
		return vs[0].([]*App)[vs[1].(int)]
	}).(AppOutput)
}

type AppMapOutput struct{ *pulumi.OutputState }

func (AppMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*App)(nil)).Elem()
}

func (o AppMapOutput) ToAppMapOutput() AppMapOutput {
	return o
}

func (o AppMapOutput) ToAppMapOutputWithContext(ctx context.Context) AppMapOutput {
	return o
}

func (o AppMapOutput) MapIndex(k pulumi.StringInput) AppOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *App {
		return vs[0].(map[string]*App)[vs[1].(string)]
	}).(AppOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AppInput)(nil)).Elem(), &App{})
	pulumi.RegisterInputType(reflect.TypeOf((*AppArrayInput)(nil)).Elem(), AppArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*AppMapInput)(nil)).Elem(), AppMap{})
	pulumi.RegisterOutputType(AppOutput{})
	pulumi.RegisterOutputType(AppArrayOutput{})
	pulumi.RegisterOutputType(AppMapOutput{})
}
