# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'AppsDashboardDashboardV2beta1MetadataArgs',
    'AppsDashboardDashboardV2beta1MetadataArgsDict',
    'AppsDashboardDashboardV2beta1OptionsArgs',
    'AppsDashboardDashboardV2beta1OptionsArgsDict',
    'AppsDashboardDashboardV2beta1SpecArgs',
    'AppsDashboardDashboardV2beta1SpecArgsDict',
    'AppsNotificationsInhibitionruleV1beta1MetadataArgs',
    'AppsNotificationsInhibitionruleV1beta1MetadataArgsDict',
    'AppsNotificationsInhibitionruleV1beta1OptionsArgs',
    'AppsNotificationsInhibitionruleV1beta1OptionsArgsDict',
    'AppsNotificationsInhibitionruleV1beta1SpecArgs',
    'AppsNotificationsInhibitionruleV1beta1SpecArgsDict',
    'AppsNotificationsInhibitionruleV1beta1SpecSourceMatcherArgs',
    'AppsNotificationsInhibitionruleV1beta1SpecSourceMatcherArgsDict',
    'AppsNotificationsInhibitionruleV1beta1SpecTargetMatcherArgs',
    'AppsNotificationsInhibitionruleV1beta1SpecTargetMatcherArgsDict',
    'AppsProvisioningConnectionV0alpha1MetadataArgs',
    'AppsProvisioningConnectionV0alpha1MetadataArgsDict',
    'AppsProvisioningConnectionV0alpha1OptionsArgs',
    'AppsProvisioningConnectionV0alpha1OptionsArgsDict',
    'AppsProvisioningConnectionV0alpha1SecureArgs',
    'AppsProvisioningConnectionV0alpha1SecureArgsDict',
    'AppsProvisioningConnectionV0alpha1SpecArgs',
    'AppsProvisioningConnectionV0alpha1SpecArgsDict',
    'AppsProvisioningConnectionV0alpha1SpecGithubArgs',
    'AppsProvisioningConnectionV0alpha1SpecGithubArgsDict',
    'AppsProvisioningRepositoryV0alpha1MetadataArgs',
    'AppsProvisioningRepositoryV0alpha1MetadataArgsDict',
    'AppsProvisioningRepositoryV0alpha1OptionsArgs',
    'AppsProvisioningRepositoryV0alpha1OptionsArgsDict',
    'AppsProvisioningRepositoryV0alpha1SecureArgs',
    'AppsProvisioningRepositoryV0alpha1SecureArgsDict',
    'AppsProvisioningRepositoryV0alpha1SpecArgs',
    'AppsProvisioningRepositoryV0alpha1SpecArgsDict',
    'AppsProvisioningRepositoryV0alpha1SpecBitbucketArgs',
    'AppsProvisioningRepositoryV0alpha1SpecBitbucketArgsDict',
    'AppsProvisioningRepositoryV0alpha1SpecConnectionArgs',
    'AppsProvisioningRepositoryV0alpha1SpecConnectionArgsDict',
    'AppsProvisioningRepositoryV0alpha1SpecGitArgs',
    'AppsProvisioningRepositoryV0alpha1SpecGitArgsDict',
    'AppsProvisioningRepositoryV0alpha1SpecGithubArgs',
    'AppsProvisioningRepositoryV0alpha1SpecGithubArgsDict',
    'AppsProvisioningRepositoryV0alpha1SpecGitlabArgs',
    'AppsProvisioningRepositoryV0alpha1SpecGitlabArgsDict',
    'AppsProvisioningRepositoryV0alpha1SpecLocalArgs',
    'AppsProvisioningRepositoryV0alpha1SpecLocalArgsDict',
    'AppsProvisioningRepositoryV0alpha1SpecSyncArgs',
    'AppsProvisioningRepositoryV0alpha1SpecSyncArgsDict',
    'AppsSecretKeeperActivationV1beta1MetadataArgs',
    'AppsSecretKeeperActivationV1beta1MetadataArgsDict',
    'AppsSecretKeeperV1beta1MetadataArgs',
    'AppsSecretKeeperV1beta1MetadataArgsDict',
    'AppsSecretKeeperV1beta1OptionsArgs',
    'AppsSecretKeeperV1beta1OptionsArgsDict',
    'AppsSecretKeeperV1beta1SpecArgs',
    'AppsSecretKeeperV1beta1SpecArgsDict',
    'AppsSecretKeeperV1beta1SpecAwsArgs',
    'AppsSecretKeeperV1beta1SpecAwsArgsDict',
    'AppsSecretKeeperV1beta1SpecAwsAssumeRoleArgs',
    'AppsSecretKeeperV1beta1SpecAwsAssumeRoleArgsDict',
    'AppsSecretSecurevalueV1beta1MetadataArgs',
    'AppsSecretSecurevalueV1beta1MetadataArgsDict',
    'AppsSecretSecurevalueV1beta1OptionsArgs',
    'AppsSecretSecurevalueV1beta1OptionsArgsDict',
    'AppsSecretSecurevalueV1beta1SpecArgs',
    'AppsSecretSecurevalueV1beta1SpecArgsDict',
]

class AppsDashboardDashboardV2beta1MetadataArgsDict(TypedDict):
    uid: pulumi.Input[_builtins.str]
    """
    The unique identifier of the resource.
    """
    annotations: NotRequired[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]
    """
    Annotations of the resource.
    """
    folder_uid: NotRequired[pulumi.Input[_builtins.str]]
    """
    The UID of the folder to save the resource in.
    """
    url: NotRequired[pulumi.Input[_builtins.str]]
    """
    The full URL of the resource.
    """
    uuid: NotRequired[pulumi.Input[_builtins.str]]
    """
    The globally unique identifier of a resource, used by the API for tracking.
    """
    version: NotRequired[pulumi.Input[_builtins.str]]
    """
    The version of the resource.
    """

@pulumi.input_type
class AppsDashboardDashboardV2beta1MetadataArgs:
    def __init__(__self__, *,
                 uid: pulumi.Input[_builtins.str],
                 annotations: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 folder_uid: Optional[pulumi.Input[_builtins.str]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None,
                 uuid: Optional[pulumi.Input[_builtins.str]] = None,
                 version: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] uid: The unique identifier of the resource.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] annotations: Annotations of the resource.
        :param pulumi.Input[_builtins.str] folder_uid: The UID of the folder to save the resource in.
        :param pulumi.Input[_builtins.str] url: The full URL of the resource.
        :param pulumi.Input[_builtins.str] uuid: The globally unique identifier of a resource, used by the API for tracking.
        :param pulumi.Input[_builtins.str] version: The version of the resource.
        """
        pulumi.set(__self__, "uid", uid)
        if annotations is not None:
            pulumi.set(__self__, "annotations", annotations)
        if folder_uid is not None:
            pulumi.set(__self__, "folder_uid", folder_uid)
        if url is not None:
            pulumi.set(__self__, "url", url)
        if uuid is not None:
            pulumi.set(__self__, "uuid", uuid)
        if version is not None:
            pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter
    def uid(self) -> pulumi.Input[_builtins.str]:
        """
        The unique identifier of the resource.
        """
        return pulumi.get(self, "uid")

    @uid.setter
    def uid(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "uid", value)

    @_builtins.property
    @pulumi.getter
    def annotations(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Annotations of the resource.
        """
        return pulumi.get(self, "annotations")

    @annotations.setter
    def annotations(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "annotations", value)

    @_builtins.property
    @pulumi.getter(name="folderUid")
    def folder_uid(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The UID of the folder to save the resource in.
        """
        return pulumi.get(self, "folder_uid")

    @folder_uid.setter
    def folder_uid(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "folder_uid", value)

    @_builtins.property
    @pulumi.getter
    def url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The full URL of the resource.
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "url", value)

    @_builtins.property
    @pulumi.getter
    def uuid(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The globally unique identifier of a resource, used by the API for tracking.
        """
        return pulumi.get(self, "uuid")

    @uuid.setter
    def uuid(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "uuid", value)

    @_builtins.property
    @pulumi.getter
    def version(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The version of the resource.
        """
        return pulumi.get(self, "version")

    @version.setter
    def version(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "version", value)


class AppsDashboardDashboardV2beta1OptionsArgsDict(TypedDict):
    allow_ui_updates: NotRequired[pulumi.Input[_builtins.bool]]
    """
    Set to true to allow editing the resource from the Grafana UI. By default, resources managed by Terraform cannot be edited in the UI. Enabling this option will cause divergence between the Terraform configuration and the resource in Grafana.
    """
    overwrite: NotRequired[pulumi.Input[_builtins.bool]]
    """
    Set to true if you want to overwrite existing resource with newer version, same resource title in folder or same resource uid.
    """

@pulumi.input_type
class AppsDashboardDashboardV2beta1OptionsArgs:
    def __init__(__self__, *,
                 allow_ui_updates: Optional[pulumi.Input[_builtins.bool]] = None,
                 overwrite: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        :param pulumi.Input[_builtins.bool] allow_ui_updates: Set to true to allow editing the resource from the Grafana UI. By default, resources managed by Terraform cannot be edited in the UI. Enabling this option will cause divergence between the Terraform configuration and the resource in Grafana.
        :param pulumi.Input[_builtins.bool] overwrite: Set to true if you want to overwrite existing resource with newer version, same resource title in folder or same resource uid.
        """
        if allow_ui_updates is not None:
            pulumi.set(__self__, "allow_ui_updates", allow_ui_updates)
        if overwrite is not None:
            pulumi.set(__self__, "overwrite", overwrite)

    @_builtins.property
    @pulumi.getter(name="allowUiUpdates")
    def allow_ui_updates(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Set to true to allow editing the resource from the Grafana UI. By default, resources managed by Terraform cannot be edited in the UI. Enabling this option will cause divergence between the Terraform configuration and the resource in Grafana.
        """
        return pulumi.get(self, "allow_ui_updates")

    @allow_ui_updates.setter
    def allow_ui_updates(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "allow_ui_updates", value)

    @_builtins.property
    @pulumi.getter
    def overwrite(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Set to true if you want to overwrite existing resource with newer version, same resource title in folder or same resource uid.
        """
        return pulumi.get(self, "overwrite")

    @overwrite.setter
    def overwrite(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "overwrite", value)


class AppsDashboardDashboardV2beta1SpecArgsDict(TypedDict):
    json: pulumi.Input[_builtins.str]
    """
    The JSON representation of the dashboard v2beta1 spec.
    """
    tags: NotRequired[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]
    """
    The tags of the dashboard. If not set, the tags will be derived from the JSON spec.
    """
    title: NotRequired[pulumi.Input[_builtins.str]]
    """
    The title of the dashboard. If not set, the title will be derived from the JSON spec.
    """

@pulumi.input_type
class AppsDashboardDashboardV2beta1SpecArgs:
    def __init__(__self__, *,
                 json: pulumi.Input[_builtins.str],
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 title: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] json: The JSON representation of the dashboard v2beta1 spec.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: The tags of the dashboard. If not set, the tags will be derived from the JSON spec.
        :param pulumi.Input[_builtins.str] title: The title of the dashboard. If not set, the title will be derived from the JSON spec.
        """
        pulumi.set(__self__, "json", json)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if title is not None:
            pulumi.set(__self__, "title", title)

    @_builtins.property
    @pulumi.getter
    def json(self) -> pulumi.Input[_builtins.str]:
        """
        The JSON representation of the dashboard v2beta1 spec.
        """
        return pulumi.get(self, "json")

    @json.setter
    def json(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "json", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        The tags of the dashboard. If not set, the tags will be derived from the JSON spec.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter
    def title(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The title of the dashboard. If not set, the title will be derived from the JSON spec.
        """
        return pulumi.get(self, "title")

    @title.setter
    def title(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "title", value)


class AppsNotificationsInhibitionruleV1beta1MetadataArgsDict(TypedDict):
    uid: pulumi.Input[_builtins.str]
    """
    The unique identifier of the resource.
    """
    annotations: NotRequired[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]
    """
    Annotations of the resource.
    """
    folder_uid: NotRequired[pulumi.Input[_builtins.str]]
    """
    The UID of the folder to save the resource in.
    """
    url: NotRequired[pulumi.Input[_builtins.str]]
    """
    The full URL of the resource.
    """
    uuid: NotRequired[pulumi.Input[_builtins.str]]
    """
    The globally unique identifier of a resource, used by the API for tracking.
    """
    version: NotRequired[pulumi.Input[_builtins.str]]
    """
    The version of the resource.
    """

@pulumi.input_type
class AppsNotificationsInhibitionruleV1beta1MetadataArgs:
    def __init__(__self__, *,
                 uid: pulumi.Input[_builtins.str],
                 annotations: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 folder_uid: Optional[pulumi.Input[_builtins.str]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None,
                 uuid: Optional[pulumi.Input[_builtins.str]] = None,
                 version: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] uid: The unique identifier of the resource.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] annotations: Annotations of the resource.
        :param pulumi.Input[_builtins.str] folder_uid: The UID of the folder to save the resource in.
        :param pulumi.Input[_builtins.str] url: The full URL of the resource.
        :param pulumi.Input[_builtins.str] uuid: The globally unique identifier of a resource, used by the API for tracking.
        :param pulumi.Input[_builtins.str] version: The version of the resource.
        """
        pulumi.set(__self__, "uid", uid)
        if annotations is not None:
            pulumi.set(__self__, "annotations", annotations)
        if folder_uid is not None:
            pulumi.set(__self__, "folder_uid", folder_uid)
        if url is not None:
            pulumi.set(__self__, "url", url)
        if uuid is not None:
            pulumi.set(__self__, "uuid", uuid)
        if version is not None:
            pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter
    def uid(self) -> pulumi.Input[_builtins.str]:
        """
        The unique identifier of the resource.
        """
        return pulumi.get(self, "uid")

    @uid.setter
    def uid(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "uid", value)

    @_builtins.property
    @pulumi.getter
    def annotations(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Annotations of the resource.
        """
        return pulumi.get(self, "annotations")

    @annotations.setter
    def annotations(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "annotations", value)

    @_builtins.property
    @pulumi.getter(name="folderUid")
    def folder_uid(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The UID of the folder to save the resource in.
        """
        return pulumi.get(self, "folder_uid")

    @folder_uid.setter
    def folder_uid(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "folder_uid", value)

    @_builtins.property
    @pulumi.getter
    def url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The full URL of the resource.
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "url", value)

    @_builtins.property
    @pulumi.getter
    def uuid(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The globally unique identifier of a resource, used by the API for tracking.
        """
        return pulumi.get(self, "uuid")

    @uuid.setter
    def uuid(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "uuid", value)

    @_builtins.property
    @pulumi.getter
    def version(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The version of the resource.
        """
        return pulumi.get(self, "version")

    @version.setter
    def version(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "version", value)


class AppsNotificationsInhibitionruleV1beta1OptionsArgsDict(TypedDict):
    overwrite: NotRequired[pulumi.Input[_builtins.bool]]
    """
    Set to true if you want to overwrite existing resource with newer version, same resource title in folder or same resource uid.
    """

@pulumi.input_type
class AppsNotificationsInhibitionruleV1beta1OptionsArgs:
    def __init__(__self__, *,
                 overwrite: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        :param pulumi.Input[_builtins.bool] overwrite: Set to true if you want to overwrite existing resource with newer version, same resource title in folder or same resource uid.
        """
        if overwrite is not None:
            pulumi.set(__self__, "overwrite", overwrite)

    @_builtins.property
    @pulumi.getter
    def overwrite(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Set to true if you want to overwrite existing resource with newer version, same resource title in folder or same resource uid.
        """
        return pulumi.get(self, "overwrite")

    @overwrite.setter
    def overwrite(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "overwrite", value)


class AppsNotificationsInhibitionruleV1beta1SpecArgsDict(TypedDict):
    equals: NotRequired[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]
    """
    Labels that must have equal values in source and target alerts for the inhibition to take effect.
    """
    source_matchers: NotRequired[pulumi.Input[Sequence[pulumi.Input['AppsNotificationsInhibitionruleV1beta1SpecSourceMatcherArgsDict']]]]
    """
    Matchers that must be satisfied for an alert to be a source of inhibition.
    """
    target_matchers: NotRequired[pulumi.Input[Sequence[pulumi.Input['AppsNotificationsInhibitionruleV1beta1SpecTargetMatcherArgsDict']]]]
    """
    Matchers that must be satisfied for an alert to be inhibited.
    """

@pulumi.input_type
class AppsNotificationsInhibitionruleV1beta1SpecArgs:
    def __init__(__self__, *,
                 equals: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 source_matchers: Optional[pulumi.Input[Sequence[pulumi.Input['AppsNotificationsInhibitionruleV1beta1SpecSourceMatcherArgs']]]] = None,
                 target_matchers: Optional[pulumi.Input[Sequence[pulumi.Input['AppsNotificationsInhibitionruleV1beta1SpecTargetMatcherArgs']]]] = None):
        """
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] equals: Labels that must have equal values in source and target alerts for the inhibition to take effect.
        :param pulumi.Input[Sequence[pulumi.Input['AppsNotificationsInhibitionruleV1beta1SpecSourceMatcherArgs']]] source_matchers: Matchers that must be satisfied for an alert to be a source of inhibition.
        :param pulumi.Input[Sequence[pulumi.Input['AppsNotificationsInhibitionruleV1beta1SpecTargetMatcherArgs']]] target_matchers: Matchers that must be satisfied for an alert to be inhibited.
        """
        if equals is not None:
            pulumi.set(__self__, "equals", equals)
        if source_matchers is not None:
            pulumi.set(__self__, "source_matchers", source_matchers)
        if target_matchers is not None:
            pulumi.set(__self__, "target_matchers", target_matchers)

    @_builtins.property
    @pulumi.getter
    def equals(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Labels that must have equal values in source and target alerts for the inhibition to take effect.
        """
        return pulumi.get(self, "equals")

    @equals.setter
    def equals(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "equals", value)

    @_builtins.property
    @pulumi.getter(name="sourceMatchers")
    def source_matchers(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['AppsNotificationsInhibitionruleV1beta1SpecSourceMatcherArgs']]]]:
        """
        Matchers that must be satisfied for an alert to be a source of inhibition.
        """
        return pulumi.get(self, "source_matchers")

    @source_matchers.setter
    def source_matchers(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['AppsNotificationsInhibitionruleV1beta1SpecSourceMatcherArgs']]]]):
        pulumi.set(self, "source_matchers", value)

    @_builtins.property
    @pulumi.getter(name="targetMatchers")
    def target_matchers(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['AppsNotificationsInhibitionruleV1beta1SpecTargetMatcherArgs']]]]:
        """
        Matchers that must be satisfied for an alert to be inhibited.
        """
        return pulumi.get(self, "target_matchers")

    @target_matchers.setter
    def target_matchers(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['AppsNotificationsInhibitionruleV1beta1SpecTargetMatcherArgs']]]]):
        pulumi.set(self, "target_matchers", value)


class AppsNotificationsInhibitionruleV1beta1SpecSourceMatcherArgsDict(TypedDict):
    label: pulumi.Input[_builtins.str]
    type: pulumi.Input[_builtins.str]
    value: pulumi.Input[_builtins.str]

@pulumi.input_type
class AppsNotificationsInhibitionruleV1beta1SpecSourceMatcherArgs:
    def __init__(__self__, *,
                 label: pulumi.Input[_builtins.str],
                 type: pulumi.Input[_builtins.str],
                 value: pulumi.Input[_builtins.str]):
        pulumi.set(__self__, "label", label)
        pulumi.set(__self__, "type", type)
        pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def label(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "label")

    @label.setter
    def label(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "label", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter
    def value(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "value")

    @value.setter
    def value(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "value", value)


class AppsNotificationsInhibitionruleV1beta1SpecTargetMatcherArgsDict(TypedDict):
    label: pulumi.Input[_builtins.str]
    type: pulumi.Input[_builtins.str]
    value: pulumi.Input[_builtins.str]

@pulumi.input_type
class AppsNotificationsInhibitionruleV1beta1SpecTargetMatcherArgs:
    def __init__(__self__, *,
                 label: pulumi.Input[_builtins.str],
                 type: pulumi.Input[_builtins.str],
                 value: pulumi.Input[_builtins.str]):
        pulumi.set(__self__, "label", label)
        pulumi.set(__self__, "type", type)
        pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def label(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "label")

    @label.setter
    def label(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "label", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter
    def value(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "value")

    @value.setter
    def value(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "value", value)


class AppsProvisioningConnectionV0alpha1MetadataArgsDict(TypedDict):
    uid: pulumi.Input[_builtins.str]
    """
    The unique identifier of the resource.
    """
    annotations: NotRequired[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]
    """
    Annotations of the resource.
    """
    folder_uid: NotRequired[pulumi.Input[_builtins.str]]
    """
    The UID of the folder to save the resource in.
    """
    url: NotRequired[pulumi.Input[_builtins.str]]
    """
    The full URL of the resource.
    """
    uuid: NotRequired[pulumi.Input[_builtins.str]]
    """
    The globally unique identifier of a resource, used by the API for tracking.
    """
    version: NotRequired[pulumi.Input[_builtins.str]]
    """
    The version of the resource.
    """

@pulumi.input_type
class AppsProvisioningConnectionV0alpha1MetadataArgs:
    def __init__(__self__, *,
                 uid: pulumi.Input[_builtins.str],
                 annotations: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 folder_uid: Optional[pulumi.Input[_builtins.str]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None,
                 uuid: Optional[pulumi.Input[_builtins.str]] = None,
                 version: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] uid: The unique identifier of the resource.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] annotations: Annotations of the resource.
        :param pulumi.Input[_builtins.str] folder_uid: The UID of the folder to save the resource in.
        :param pulumi.Input[_builtins.str] url: The full URL of the resource.
        :param pulumi.Input[_builtins.str] uuid: The globally unique identifier of a resource, used by the API for tracking.
        :param pulumi.Input[_builtins.str] version: The version of the resource.
        """
        pulumi.set(__self__, "uid", uid)
        if annotations is not None:
            pulumi.set(__self__, "annotations", annotations)
        if folder_uid is not None:
            pulumi.set(__self__, "folder_uid", folder_uid)
        if url is not None:
            pulumi.set(__self__, "url", url)
        if uuid is not None:
            pulumi.set(__self__, "uuid", uuid)
        if version is not None:
            pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter
    def uid(self) -> pulumi.Input[_builtins.str]:
        """
        The unique identifier of the resource.
        """
        return pulumi.get(self, "uid")

    @uid.setter
    def uid(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "uid", value)

    @_builtins.property
    @pulumi.getter
    def annotations(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Annotations of the resource.
        """
        return pulumi.get(self, "annotations")

    @annotations.setter
    def annotations(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "annotations", value)

    @_builtins.property
    @pulumi.getter(name="folderUid")
    def folder_uid(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The UID of the folder to save the resource in.
        """
        return pulumi.get(self, "folder_uid")

    @folder_uid.setter
    def folder_uid(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "folder_uid", value)

    @_builtins.property
    @pulumi.getter
    def url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The full URL of the resource.
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "url", value)

    @_builtins.property
    @pulumi.getter
    def uuid(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The globally unique identifier of a resource, used by the API for tracking.
        """
        return pulumi.get(self, "uuid")

    @uuid.setter
    def uuid(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "uuid", value)

    @_builtins.property
    @pulumi.getter
    def version(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The version of the resource.
        """
        return pulumi.get(self, "version")

    @version.setter
    def version(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "version", value)


class AppsProvisioningConnectionV0alpha1OptionsArgsDict(TypedDict):
    overwrite: NotRequired[pulumi.Input[_builtins.bool]]
    """
    Set to true if you want to overwrite existing resource with newer version, same resource title in folder or same resource uid.
    """

@pulumi.input_type
class AppsProvisioningConnectionV0alpha1OptionsArgs:
    def __init__(__self__, *,
                 overwrite: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        :param pulumi.Input[_builtins.bool] overwrite: Set to true if you want to overwrite existing resource with newer version, same resource title in folder or same resource uid.
        """
        if overwrite is not None:
            pulumi.set(__self__, "overwrite", overwrite)

    @_builtins.property
    @pulumi.getter
    def overwrite(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Set to true if you want to overwrite existing resource with newer version, same resource title in folder or same resource uid.
        """
        return pulumi.get(self, "overwrite")

    @overwrite.setter
    def overwrite(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "overwrite", value)


class AppsProvisioningConnectionV0alpha1SecureArgsDict(TypedDict):
    private_key: NotRequired[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]
    """
    **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
    Private key for GitHub App authentication.
    """
    token: NotRequired[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]
    """
    **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
    Access token.
    """

@pulumi.input_type
class AppsProvisioningConnectionV0alpha1SecureArgs:
    def __init__(__self__, *,
                 private_key: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 token: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None):
        """
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] private_key: **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
               Private key for GitHub App authentication.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] token: **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
               Access token.
        """
        if private_key is not None:
            pulumi.set(__self__, "private_key", private_key)
        if token is not None:
            pulumi.set(__self__, "token", token)

    @_builtins.property
    @pulumi.getter(name="privateKey")
    def private_key(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        Private key for GitHub App authentication.
        """
        return pulumi.get(self, "private_key")

    @private_key.setter
    def private_key(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "private_key", value)

    @_builtins.property
    @pulumi.getter
    def token(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        Access token.
        """
        return pulumi.get(self, "token")

    @token.setter
    def token(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "token", value)


class AppsProvisioningConnectionV0alpha1SpecArgsDict(TypedDict):
    title: pulumi.Input[_builtins.str]
    """
    Display name shown in the UI.
    """
    type: pulumi.Input[_builtins.str]
    """
    Connection provider type.
    """
    description: NotRequired[pulumi.Input[_builtins.str]]
    """
    Connection description.
    """
    github: NotRequired[pulumi.Input['AppsProvisioningConnectionV0alpha1SpecGithubArgsDict']]
    """
    GitHub App configuration.
    """
    url: NotRequired[pulumi.Input[_builtins.str]]
    """
    Provider URL.
    """

@pulumi.input_type
class AppsProvisioningConnectionV0alpha1SpecArgs:
    def __init__(__self__, *,
                 title: pulumi.Input[_builtins.str],
                 type: pulumi.Input[_builtins.str],
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 github: Optional[pulumi.Input['AppsProvisioningConnectionV0alpha1SpecGithubArgs']] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] title: Display name shown in the UI.
        :param pulumi.Input[_builtins.str] type: Connection provider type.
        :param pulumi.Input[_builtins.str] description: Connection description.
        :param pulumi.Input['AppsProvisioningConnectionV0alpha1SpecGithubArgs'] github: GitHub App configuration.
        :param pulumi.Input[_builtins.str] url: Provider URL.
        """
        pulumi.set(__self__, "title", title)
        pulumi.set(__self__, "type", type)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if github is not None:
            pulumi.set(__self__, "github", github)
        if url is not None:
            pulumi.set(__self__, "url", url)

    @_builtins.property
    @pulumi.getter
    def title(self) -> pulumi.Input[_builtins.str]:
        """
        Display name shown in the UI.
        """
        return pulumi.get(self, "title")

    @title.setter
    def title(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "title", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[_builtins.str]:
        """
        Connection provider type.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Connection description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def github(self) -> Optional[pulumi.Input['AppsProvisioningConnectionV0alpha1SpecGithubArgs']]:
        """
        GitHub App configuration.
        """
        return pulumi.get(self, "github")

    @github.setter
    def github(self, value: Optional[pulumi.Input['AppsProvisioningConnectionV0alpha1SpecGithubArgs']]):
        pulumi.set(self, "github", value)

    @_builtins.property
    @pulumi.getter
    def url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Provider URL.
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "url", value)


class AppsProvisioningConnectionV0alpha1SpecGithubArgsDict(TypedDict):
    app_id: pulumi.Input[_builtins.str]
    """
    GitHub App ID.
    """
    installation_id: pulumi.Input[_builtins.str]
    """
    GitHub App installation ID.
    """

@pulumi.input_type
class AppsProvisioningConnectionV0alpha1SpecGithubArgs:
    def __init__(__self__, *,
                 app_id: pulumi.Input[_builtins.str],
                 installation_id: pulumi.Input[_builtins.str]):
        """
        :param pulumi.Input[_builtins.str] app_id: GitHub App ID.
        :param pulumi.Input[_builtins.str] installation_id: GitHub App installation ID.
        """
        pulumi.set(__self__, "app_id", app_id)
        pulumi.set(__self__, "installation_id", installation_id)

    @_builtins.property
    @pulumi.getter(name="appId")
    def app_id(self) -> pulumi.Input[_builtins.str]:
        """
        GitHub App ID.
        """
        return pulumi.get(self, "app_id")

    @app_id.setter
    def app_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "app_id", value)

    @_builtins.property
    @pulumi.getter(name="installationId")
    def installation_id(self) -> pulumi.Input[_builtins.str]:
        """
        GitHub App installation ID.
        """
        return pulumi.get(self, "installation_id")

    @installation_id.setter
    def installation_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "installation_id", value)


class AppsProvisioningRepositoryV0alpha1MetadataArgsDict(TypedDict):
    uid: pulumi.Input[_builtins.str]
    """
    The unique identifier of the resource.
    """
    annotations: NotRequired[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]
    """
    Annotations of the resource.
    """
    folder_uid: NotRequired[pulumi.Input[_builtins.str]]
    """
    The UID of the folder to save the resource in.
    """
    url: NotRequired[pulumi.Input[_builtins.str]]
    """
    The full URL of the resource.
    """
    uuid: NotRequired[pulumi.Input[_builtins.str]]
    """
    The globally unique identifier of a resource, used by the API for tracking.
    """
    version: NotRequired[pulumi.Input[_builtins.str]]
    """
    The version of the resource.
    """

@pulumi.input_type
class AppsProvisioningRepositoryV0alpha1MetadataArgs:
    def __init__(__self__, *,
                 uid: pulumi.Input[_builtins.str],
                 annotations: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 folder_uid: Optional[pulumi.Input[_builtins.str]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None,
                 uuid: Optional[pulumi.Input[_builtins.str]] = None,
                 version: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] uid: The unique identifier of the resource.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] annotations: Annotations of the resource.
        :param pulumi.Input[_builtins.str] folder_uid: The UID of the folder to save the resource in.
        :param pulumi.Input[_builtins.str] url: The full URL of the resource.
        :param pulumi.Input[_builtins.str] uuid: The globally unique identifier of a resource, used by the API for tracking.
        :param pulumi.Input[_builtins.str] version: The version of the resource.
        """
        pulumi.set(__self__, "uid", uid)
        if annotations is not None:
            pulumi.set(__self__, "annotations", annotations)
        if folder_uid is not None:
            pulumi.set(__self__, "folder_uid", folder_uid)
        if url is not None:
            pulumi.set(__self__, "url", url)
        if uuid is not None:
            pulumi.set(__self__, "uuid", uuid)
        if version is not None:
            pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter
    def uid(self) -> pulumi.Input[_builtins.str]:
        """
        The unique identifier of the resource.
        """
        return pulumi.get(self, "uid")

    @uid.setter
    def uid(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "uid", value)

    @_builtins.property
    @pulumi.getter
    def annotations(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Annotations of the resource.
        """
        return pulumi.get(self, "annotations")

    @annotations.setter
    def annotations(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "annotations", value)

    @_builtins.property
    @pulumi.getter(name="folderUid")
    def folder_uid(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The UID of the folder to save the resource in.
        """
        return pulumi.get(self, "folder_uid")

    @folder_uid.setter
    def folder_uid(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "folder_uid", value)

    @_builtins.property
    @pulumi.getter
    def url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The full URL of the resource.
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "url", value)

    @_builtins.property
    @pulumi.getter
    def uuid(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The globally unique identifier of a resource, used by the API for tracking.
        """
        return pulumi.get(self, "uuid")

    @uuid.setter
    def uuid(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "uuid", value)

    @_builtins.property
    @pulumi.getter
    def version(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The version of the resource.
        """
        return pulumi.get(self, "version")

    @version.setter
    def version(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "version", value)


class AppsProvisioningRepositoryV0alpha1OptionsArgsDict(TypedDict):
    overwrite: NotRequired[pulumi.Input[_builtins.bool]]
    """
    Set to true if you want to overwrite existing resource with newer version, same resource title in folder or same resource uid.
    """

@pulumi.input_type
class AppsProvisioningRepositoryV0alpha1OptionsArgs:
    def __init__(__self__, *,
                 overwrite: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        :param pulumi.Input[_builtins.bool] overwrite: Set to true if you want to overwrite existing resource with newer version, same resource title in folder or same resource uid.
        """
        if overwrite is not None:
            pulumi.set(__self__, "overwrite", overwrite)

    @_builtins.property
    @pulumi.getter
    def overwrite(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Set to true if you want to overwrite existing resource with newer version, same resource title in folder or same resource uid.
        """
        return pulumi.get(self, "overwrite")

    @overwrite.setter
    def overwrite(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "overwrite", value)


class AppsProvisioningRepositoryV0alpha1SecureArgsDict(TypedDict):
    token: NotRequired[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]
    """
    **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
    Token for repository authentication.
    """
    webhook_secret: NotRequired[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]
    """
    **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
    Webhook secret.
    """

@pulumi.input_type
class AppsProvisioningRepositoryV0alpha1SecureArgs:
    def __init__(__self__, *,
                 token: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 webhook_secret: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None):
        """
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] token: **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
               Token for repository authentication.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] webhook_secret: **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
               Webhook secret.
        """
        if token is not None:
            pulumi.set(__self__, "token", token)
        if webhook_secret is not None:
            pulumi.set(__self__, "webhook_secret", webhook_secret)

    @_builtins.property
    @pulumi.getter
    def token(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        Token for repository authentication.
        """
        return pulumi.get(self, "token")

    @token.setter
    def token(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "token", value)

    @_builtins.property
    @pulumi.getter(name="webhookSecret")
    def webhook_secret(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        Webhook secret.
        """
        return pulumi.get(self, "webhook_secret")

    @webhook_secret.setter
    def webhook_secret(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "webhook_secret", value)


class AppsProvisioningRepositoryV0alpha1SpecArgsDict(TypedDict):
    title: pulumi.Input[_builtins.str]
    """
    Display name shown in the UI.
    """
    type: pulumi.Input[_builtins.str]
    """
    Repository provider type: local, github, git, bitbucket, or gitlab.
    """
    bitbucket: NotRequired[pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecBitbucketArgsDict']]
    """
    Bitbucket repository configuration.
    """
    connection: NotRequired[pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecConnectionArgsDict']]
    """
    Connection resource reference.
    """
    description: NotRequired[pulumi.Input[_builtins.str]]
    """
    Repository description.
    """
    git: NotRequired[pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecGitArgsDict']]
    """
    Generic git repository configuration.
    """
    github: NotRequired[pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecGithubArgsDict']]
    """
    GitHub repository configuration.
    """
    gitlab: NotRequired[pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecGitlabArgsDict']]
    """
    GitLab repository configuration.
    """
    local: NotRequired[pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecLocalArgsDict']]
    """
    Local filesystem repository configuration.
    """
    sync: NotRequired[pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecSyncArgsDict']]
    """
    Sync configuration.
    """
    workflows: NotRequired[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]
    """
    Allowed change workflows: write, branch.
    """

@pulumi.input_type
class AppsProvisioningRepositoryV0alpha1SpecArgs:
    def __init__(__self__, *,
                 title: pulumi.Input[_builtins.str],
                 type: pulumi.Input[_builtins.str],
                 bitbucket: Optional[pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecBitbucketArgs']] = None,
                 connection: Optional[pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecConnectionArgs']] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 git: Optional[pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecGitArgs']] = None,
                 github: Optional[pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecGithubArgs']] = None,
                 gitlab: Optional[pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecGitlabArgs']] = None,
                 local: Optional[pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecLocalArgs']] = None,
                 sync: Optional[pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecSyncArgs']] = None,
                 workflows: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        :param pulumi.Input[_builtins.str] title: Display name shown in the UI.
        :param pulumi.Input[_builtins.str] type: Repository provider type: local, github, git, bitbucket, or gitlab.
        :param pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecBitbucketArgs'] bitbucket: Bitbucket repository configuration.
        :param pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecConnectionArgs'] connection: Connection resource reference.
        :param pulumi.Input[_builtins.str] description: Repository description.
        :param pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecGitArgs'] git: Generic git repository configuration.
        :param pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecGithubArgs'] github: GitHub repository configuration.
        :param pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecGitlabArgs'] gitlab: GitLab repository configuration.
        :param pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecLocalArgs'] local: Local filesystem repository configuration.
        :param pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecSyncArgs'] sync: Sync configuration.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] workflows: Allowed change workflows: write, branch.
        """
        pulumi.set(__self__, "title", title)
        pulumi.set(__self__, "type", type)
        if bitbucket is not None:
            pulumi.set(__self__, "bitbucket", bitbucket)
        if connection is not None:
            pulumi.set(__self__, "connection", connection)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if git is not None:
            pulumi.set(__self__, "git", git)
        if github is not None:
            pulumi.set(__self__, "github", github)
        if gitlab is not None:
            pulumi.set(__self__, "gitlab", gitlab)
        if local is not None:
            pulumi.set(__self__, "local", local)
        if sync is not None:
            pulumi.set(__self__, "sync", sync)
        if workflows is not None:
            pulumi.set(__self__, "workflows", workflows)

    @_builtins.property
    @pulumi.getter
    def title(self) -> pulumi.Input[_builtins.str]:
        """
        Display name shown in the UI.
        """
        return pulumi.get(self, "title")

    @title.setter
    def title(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "title", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[_builtins.str]:
        """
        Repository provider type: local, github, git, bitbucket, or gitlab.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter
    def bitbucket(self) -> Optional[pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecBitbucketArgs']]:
        """
        Bitbucket repository configuration.
        """
        return pulumi.get(self, "bitbucket")

    @bitbucket.setter
    def bitbucket(self, value: Optional[pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecBitbucketArgs']]):
        pulumi.set(self, "bitbucket", value)

    @_builtins.property
    @pulumi.getter
    def connection(self) -> Optional[pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecConnectionArgs']]:
        """
        Connection resource reference.
        """
        return pulumi.get(self, "connection")

    @connection.setter
    def connection(self, value: Optional[pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecConnectionArgs']]):
        pulumi.set(self, "connection", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Repository description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def git(self) -> Optional[pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecGitArgs']]:
        """
        Generic git repository configuration.
        """
        return pulumi.get(self, "git")

    @git.setter
    def git(self, value: Optional[pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecGitArgs']]):
        pulumi.set(self, "git", value)

    @_builtins.property
    @pulumi.getter
    def github(self) -> Optional[pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecGithubArgs']]:
        """
        GitHub repository configuration.
        """
        return pulumi.get(self, "github")

    @github.setter
    def github(self, value: Optional[pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecGithubArgs']]):
        pulumi.set(self, "github", value)

    @_builtins.property
    @pulumi.getter
    def gitlab(self) -> Optional[pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecGitlabArgs']]:
        """
        GitLab repository configuration.
        """
        return pulumi.get(self, "gitlab")

    @gitlab.setter
    def gitlab(self, value: Optional[pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecGitlabArgs']]):
        pulumi.set(self, "gitlab", value)

    @_builtins.property
    @pulumi.getter
    def local(self) -> Optional[pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecLocalArgs']]:
        """
        Local filesystem repository configuration.
        """
        return pulumi.get(self, "local")

    @local.setter
    def local(self, value: Optional[pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecLocalArgs']]):
        pulumi.set(self, "local", value)

    @_builtins.property
    @pulumi.getter
    def sync(self) -> Optional[pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecSyncArgs']]:
        """
        Sync configuration.
        """
        return pulumi.get(self, "sync")

    @sync.setter
    def sync(self, value: Optional[pulumi.Input['AppsProvisioningRepositoryV0alpha1SpecSyncArgs']]):
        pulumi.set(self, "sync", value)

    @_builtins.property
    @pulumi.getter
    def workflows(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Allowed change workflows: write, branch.
        """
        return pulumi.get(self, "workflows")

    @workflows.setter
    def workflows(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "workflows", value)


class AppsProvisioningRepositoryV0alpha1SpecBitbucketArgsDict(TypedDict):
    branch: NotRequired[pulumi.Input[_builtins.str]]
    """
    Branch to sync.
    """
    path: NotRequired[pulumi.Input[_builtins.str]]
    """
    Optional subdirectory path.
    """
    token_user: NotRequired[pulumi.Input[_builtins.str]]
    """
    Username for PAT auth.
    """
    url: NotRequired[pulumi.Input[_builtins.str]]
    """
    Repository URL.
    """

@pulumi.input_type
class AppsProvisioningRepositoryV0alpha1SpecBitbucketArgs:
    def __init__(__self__, *,
                 branch: Optional[pulumi.Input[_builtins.str]] = None,
                 path: Optional[pulumi.Input[_builtins.str]] = None,
                 token_user: Optional[pulumi.Input[_builtins.str]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] branch: Branch to sync.
        :param pulumi.Input[_builtins.str] path: Optional subdirectory path.
        :param pulumi.Input[_builtins.str] token_user: Username for PAT auth.
        :param pulumi.Input[_builtins.str] url: Repository URL.
        """
        if branch is not None:
            pulumi.set(__self__, "branch", branch)
        if path is not None:
            pulumi.set(__self__, "path", path)
        if token_user is not None:
            pulumi.set(__self__, "token_user", token_user)
        if url is not None:
            pulumi.set(__self__, "url", url)

    @_builtins.property
    @pulumi.getter
    def branch(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Branch to sync.
        """
        return pulumi.get(self, "branch")

    @branch.setter
    def branch(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "branch", value)

    @_builtins.property
    @pulumi.getter
    def path(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Optional subdirectory path.
        """
        return pulumi.get(self, "path")

    @path.setter
    def path(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "path", value)

    @_builtins.property
    @pulumi.getter(name="tokenUser")
    def token_user(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Username for PAT auth.
        """
        return pulumi.get(self, "token_user")

    @token_user.setter
    def token_user(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "token_user", value)

    @_builtins.property
    @pulumi.getter
    def url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Repository URL.
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "url", value)


class AppsProvisioningRepositoryV0alpha1SpecConnectionArgsDict(TypedDict):
    name: NotRequired[pulumi.Input[_builtins.str]]
    """
    Connection resource name.
    """

@pulumi.input_type
class AppsProvisioningRepositoryV0alpha1SpecConnectionArgs:
    def __init__(__self__, *,
                 name: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] name: Connection resource name.
        """
        if name is not None:
            pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Connection resource name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)


class AppsProvisioningRepositoryV0alpha1SpecGitArgsDict(TypedDict):
    branch: NotRequired[pulumi.Input[_builtins.str]]
    """
    Branch to sync.
    """
    path: NotRequired[pulumi.Input[_builtins.str]]
    """
    Optional subdirectory path.
    """
    token_user: NotRequired[pulumi.Input[_builtins.str]]
    """
    Username for PAT auth.
    """
    url: NotRequired[pulumi.Input[_builtins.str]]
    """
    Repository URL.
    """

@pulumi.input_type
class AppsProvisioningRepositoryV0alpha1SpecGitArgs:
    def __init__(__self__, *,
                 branch: Optional[pulumi.Input[_builtins.str]] = None,
                 path: Optional[pulumi.Input[_builtins.str]] = None,
                 token_user: Optional[pulumi.Input[_builtins.str]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] branch: Branch to sync.
        :param pulumi.Input[_builtins.str] path: Optional subdirectory path.
        :param pulumi.Input[_builtins.str] token_user: Username for PAT auth.
        :param pulumi.Input[_builtins.str] url: Repository URL.
        """
        if branch is not None:
            pulumi.set(__self__, "branch", branch)
        if path is not None:
            pulumi.set(__self__, "path", path)
        if token_user is not None:
            pulumi.set(__self__, "token_user", token_user)
        if url is not None:
            pulumi.set(__self__, "url", url)

    @_builtins.property
    @pulumi.getter
    def branch(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Branch to sync.
        """
        return pulumi.get(self, "branch")

    @branch.setter
    def branch(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "branch", value)

    @_builtins.property
    @pulumi.getter
    def path(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Optional subdirectory path.
        """
        return pulumi.get(self, "path")

    @path.setter
    def path(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "path", value)

    @_builtins.property
    @pulumi.getter(name="tokenUser")
    def token_user(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Username for PAT auth.
        """
        return pulumi.get(self, "token_user")

    @token_user.setter
    def token_user(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "token_user", value)

    @_builtins.property
    @pulumi.getter
    def url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Repository URL.
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "url", value)


class AppsProvisioningRepositoryV0alpha1SpecGithubArgsDict(TypedDict):
    branch: NotRequired[pulumi.Input[_builtins.str]]
    """
    Branch to sync.
    """
    generate_dashboard_previews: NotRequired[pulumi.Input[_builtins.bool]]
    """
    Whether to generate dashboard previews.
    """
    path: NotRequired[pulumi.Input[_builtins.str]]
    """
    Optional subdirectory path.
    """
    url: NotRequired[pulumi.Input[_builtins.str]]
    """
    Repository URL.
    """

@pulumi.input_type
class AppsProvisioningRepositoryV0alpha1SpecGithubArgs:
    def __init__(__self__, *,
                 branch: Optional[pulumi.Input[_builtins.str]] = None,
                 generate_dashboard_previews: Optional[pulumi.Input[_builtins.bool]] = None,
                 path: Optional[pulumi.Input[_builtins.str]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] branch: Branch to sync.
        :param pulumi.Input[_builtins.bool] generate_dashboard_previews: Whether to generate dashboard previews.
        :param pulumi.Input[_builtins.str] path: Optional subdirectory path.
        :param pulumi.Input[_builtins.str] url: Repository URL.
        """
        if branch is not None:
            pulumi.set(__self__, "branch", branch)
        if generate_dashboard_previews is not None:
            pulumi.set(__self__, "generate_dashboard_previews", generate_dashboard_previews)
        if path is not None:
            pulumi.set(__self__, "path", path)
        if url is not None:
            pulumi.set(__self__, "url", url)

    @_builtins.property
    @pulumi.getter
    def branch(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Branch to sync.
        """
        return pulumi.get(self, "branch")

    @branch.setter
    def branch(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "branch", value)

    @_builtins.property
    @pulumi.getter(name="generateDashboardPreviews")
    def generate_dashboard_previews(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether to generate dashboard previews.
        """
        return pulumi.get(self, "generate_dashboard_previews")

    @generate_dashboard_previews.setter
    def generate_dashboard_previews(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "generate_dashboard_previews", value)

    @_builtins.property
    @pulumi.getter
    def path(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Optional subdirectory path.
        """
        return pulumi.get(self, "path")

    @path.setter
    def path(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "path", value)

    @_builtins.property
    @pulumi.getter
    def url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Repository URL.
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "url", value)


class AppsProvisioningRepositoryV0alpha1SpecGitlabArgsDict(TypedDict):
    branch: NotRequired[pulumi.Input[_builtins.str]]
    """
    Branch to sync.
    """
    path: NotRequired[pulumi.Input[_builtins.str]]
    """
    Optional subdirectory path.
    """
    url: NotRequired[pulumi.Input[_builtins.str]]
    """
    Repository URL.
    """

@pulumi.input_type
class AppsProvisioningRepositoryV0alpha1SpecGitlabArgs:
    def __init__(__self__, *,
                 branch: Optional[pulumi.Input[_builtins.str]] = None,
                 path: Optional[pulumi.Input[_builtins.str]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] branch: Branch to sync.
        :param pulumi.Input[_builtins.str] path: Optional subdirectory path.
        :param pulumi.Input[_builtins.str] url: Repository URL.
        """
        if branch is not None:
            pulumi.set(__self__, "branch", branch)
        if path is not None:
            pulumi.set(__self__, "path", path)
        if url is not None:
            pulumi.set(__self__, "url", url)

    @_builtins.property
    @pulumi.getter
    def branch(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Branch to sync.
        """
        return pulumi.get(self, "branch")

    @branch.setter
    def branch(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "branch", value)

    @_builtins.property
    @pulumi.getter
    def path(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Optional subdirectory path.
        """
        return pulumi.get(self, "path")

    @path.setter
    def path(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "path", value)

    @_builtins.property
    @pulumi.getter
    def url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Repository URL.
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "url", value)


class AppsProvisioningRepositoryV0alpha1SpecLocalArgsDict(TypedDict):
    path: NotRequired[pulumi.Input[_builtins.str]]
    """
    Filesystem path.
    """

@pulumi.input_type
class AppsProvisioningRepositoryV0alpha1SpecLocalArgs:
    def __init__(__self__, *,
                 path: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] path: Filesystem path.
        """
        if path is not None:
            pulumi.set(__self__, "path", path)

    @_builtins.property
    @pulumi.getter
    def path(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Filesystem path.
        """
        return pulumi.get(self, "path")

    @path.setter
    def path(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "path", value)


class AppsProvisioningRepositoryV0alpha1SpecSyncArgsDict(TypedDict):
    enabled: pulumi.Input[_builtins.bool]
    """
    Whether sync is enabled.
    """
    target: pulumi.Input[_builtins.str]
    """
    Sync target: instance or folder.
    """
    interval_seconds: NotRequired[pulumi.Input[_builtins.int]]
    """
    Sync interval in seconds.
    """

@pulumi.input_type
class AppsProvisioningRepositoryV0alpha1SpecSyncArgs:
    def __init__(__self__, *,
                 enabled: pulumi.Input[_builtins.bool],
                 target: pulumi.Input[_builtins.str],
                 interval_seconds: Optional[pulumi.Input[_builtins.int]] = None):
        """
        :param pulumi.Input[_builtins.bool] enabled: Whether sync is enabled.
        :param pulumi.Input[_builtins.str] target: Sync target: instance or folder.
        :param pulumi.Input[_builtins.int] interval_seconds: Sync interval in seconds.
        """
        pulumi.set(__self__, "enabled", enabled)
        pulumi.set(__self__, "target", target)
        if interval_seconds is not None:
            pulumi.set(__self__, "interval_seconds", interval_seconds)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[_builtins.bool]:
        """
        Whether sync is enabled.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[_builtins.bool]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter
    def target(self) -> pulumi.Input[_builtins.str]:
        """
        Sync target: instance or folder.
        """
        return pulumi.get(self, "target")

    @target.setter
    def target(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "target", value)

    @_builtins.property
    @pulumi.getter(name="intervalSeconds")
    def interval_seconds(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Sync interval in seconds.
        """
        return pulumi.get(self, "interval_seconds")

    @interval_seconds.setter
    def interval_seconds(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "interval_seconds", value)


class AppsSecretKeeperActivationV1beta1MetadataArgsDict(TypedDict):
    uid: pulumi.Input[_builtins.str]
    """
    The unique identifier of the resource.
    """
    annotations: NotRequired[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]
    """
    Annotations of the resource.
    """
    folder_uid: NotRequired[pulumi.Input[_builtins.str]]
    """
    The UID of the folder to save the resource in.
    """
    url: NotRequired[pulumi.Input[_builtins.str]]
    """
    The full URL of the resource.
    """
    uuid: NotRequired[pulumi.Input[_builtins.str]]
    """
    The globally unique identifier of a resource, used by the API for tracking.
    """
    version: NotRequired[pulumi.Input[_builtins.str]]
    """
    The version of the resource.
    """

@pulumi.input_type
class AppsSecretKeeperActivationV1beta1MetadataArgs:
    def __init__(__self__, *,
                 uid: pulumi.Input[_builtins.str],
                 annotations: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 folder_uid: Optional[pulumi.Input[_builtins.str]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None,
                 uuid: Optional[pulumi.Input[_builtins.str]] = None,
                 version: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] uid: The unique identifier of the resource.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] annotations: Annotations of the resource.
        :param pulumi.Input[_builtins.str] folder_uid: The UID of the folder to save the resource in.
        :param pulumi.Input[_builtins.str] url: The full URL of the resource.
        :param pulumi.Input[_builtins.str] uuid: The globally unique identifier of a resource, used by the API for tracking.
        :param pulumi.Input[_builtins.str] version: The version of the resource.
        """
        pulumi.set(__self__, "uid", uid)
        if annotations is not None:
            pulumi.set(__self__, "annotations", annotations)
        if folder_uid is not None:
            pulumi.set(__self__, "folder_uid", folder_uid)
        if url is not None:
            pulumi.set(__self__, "url", url)
        if uuid is not None:
            pulumi.set(__self__, "uuid", uuid)
        if version is not None:
            pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter
    def uid(self) -> pulumi.Input[_builtins.str]:
        """
        The unique identifier of the resource.
        """
        return pulumi.get(self, "uid")

    @uid.setter
    def uid(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "uid", value)

    @_builtins.property
    @pulumi.getter
    def annotations(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Annotations of the resource.
        """
        return pulumi.get(self, "annotations")

    @annotations.setter
    def annotations(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "annotations", value)

    @_builtins.property
    @pulumi.getter(name="folderUid")
    def folder_uid(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The UID of the folder to save the resource in.
        """
        return pulumi.get(self, "folder_uid")

    @folder_uid.setter
    def folder_uid(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "folder_uid", value)

    @_builtins.property
    @pulumi.getter
    def url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The full URL of the resource.
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "url", value)

    @_builtins.property
    @pulumi.getter
    def uuid(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The globally unique identifier of a resource, used by the API for tracking.
        """
        return pulumi.get(self, "uuid")

    @uuid.setter
    def uuid(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "uuid", value)

    @_builtins.property
    @pulumi.getter
    def version(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The version of the resource.
        """
        return pulumi.get(self, "version")

    @version.setter
    def version(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "version", value)


class AppsSecretKeeperV1beta1MetadataArgsDict(TypedDict):
    uid: pulumi.Input[_builtins.str]
    """
    The unique identifier of the resource.
    """
    annotations: NotRequired[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]
    """
    Annotations of the resource.
    """
    folder_uid: NotRequired[pulumi.Input[_builtins.str]]
    """
    The UID of the folder to save the resource in.
    """
    url: NotRequired[pulumi.Input[_builtins.str]]
    """
    The full URL of the resource.
    """
    uuid: NotRequired[pulumi.Input[_builtins.str]]
    """
    The globally unique identifier of a resource, used by the API for tracking.
    """
    version: NotRequired[pulumi.Input[_builtins.str]]
    """
    The version of the resource.
    """

@pulumi.input_type
class AppsSecretKeeperV1beta1MetadataArgs:
    def __init__(__self__, *,
                 uid: pulumi.Input[_builtins.str],
                 annotations: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 folder_uid: Optional[pulumi.Input[_builtins.str]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None,
                 uuid: Optional[pulumi.Input[_builtins.str]] = None,
                 version: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] uid: The unique identifier of the resource.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] annotations: Annotations of the resource.
        :param pulumi.Input[_builtins.str] folder_uid: The UID of the folder to save the resource in.
        :param pulumi.Input[_builtins.str] url: The full URL of the resource.
        :param pulumi.Input[_builtins.str] uuid: The globally unique identifier of a resource, used by the API for tracking.
        :param pulumi.Input[_builtins.str] version: The version of the resource.
        """
        pulumi.set(__self__, "uid", uid)
        if annotations is not None:
            pulumi.set(__self__, "annotations", annotations)
        if folder_uid is not None:
            pulumi.set(__self__, "folder_uid", folder_uid)
        if url is not None:
            pulumi.set(__self__, "url", url)
        if uuid is not None:
            pulumi.set(__self__, "uuid", uuid)
        if version is not None:
            pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter
    def uid(self) -> pulumi.Input[_builtins.str]:
        """
        The unique identifier of the resource.
        """
        return pulumi.get(self, "uid")

    @uid.setter
    def uid(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "uid", value)

    @_builtins.property
    @pulumi.getter
    def annotations(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Annotations of the resource.
        """
        return pulumi.get(self, "annotations")

    @annotations.setter
    def annotations(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "annotations", value)

    @_builtins.property
    @pulumi.getter(name="folderUid")
    def folder_uid(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The UID of the folder to save the resource in.
        """
        return pulumi.get(self, "folder_uid")

    @folder_uid.setter
    def folder_uid(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "folder_uid", value)

    @_builtins.property
    @pulumi.getter
    def url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The full URL of the resource.
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "url", value)

    @_builtins.property
    @pulumi.getter
    def uuid(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The globally unique identifier of a resource, used by the API for tracking.
        """
        return pulumi.get(self, "uuid")

    @uuid.setter
    def uuid(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "uuid", value)

    @_builtins.property
    @pulumi.getter
    def version(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The version of the resource.
        """
        return pulumi.get(self, "version")

    @version.setter
    def version(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "version", value)


class AppsSecretKeeperV1beta1OptionsArgsDict(TypedDict):
    overwrite: NotRequired[pulumi.Input[_builtins.bool]]
    """
    Set to true if you want to overwrite existing resource with newer version, same resource title in folder or same resource uid.
    """

@pulumi.input_type
class AppsSecretKeeperV1beta1OptionsArgs:
    def __init__(__self__, *,
                 overwrite: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        :param pulumi.Input[_builtins.bool] overwrite: Set to true if you want to overwrite existing resource with newer version, same resource title in folder or same resource uid.
        """
        if overwrite is not None:
            pulumi.set(__self__, "overwrite", overwrite)

    @_builtins.property
    @pulumi.getter
    def overwrite(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Set to true if you want to overwrite existing resource with newer version, same resource title in folder or same resource uid.
        """
        return pulumi.get(self, "overwrite")

    @overwrite.setter
    def overwrite(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "overwrite", value)


class AppsSecretKeeperV1beta1SpecArgsDict(TypedDict):
    aws: NotRequired[pulumi.Input['AppsSecretKeeperV1beta1SpecAwsArgsDict']]
    """
    AWS Secrets Manager configuration.
    """
    description: NotRequired[pulumi.Input[_builtins.str]]
    """
    Keeper description.
    """

@pulumi.input_type
class AppsSecretKeeperV1beta1SpecArgs:
    def __init__(__self__, *,
                 aws: Optional[pulumi.Input['AppsSecretKeeperV1beta1SpecAwsArgs']] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input['AppsSecretKeeperV1beta1SpecAwsArgs'] aws: AWS Secrets Manager configuration.
        :param pulumi.Input[_builtins.str] description: Keeper description.
        """
        if aws is not None:
            pulumi.set(__self__, "aws", aws)
        if description is not None:
            pulumi.set(__self__, "description", description)

    @_builtins.property
    @pulumi.getter
    def aws(self) -> Optional[pulumi.Input['AppsSecretKeeperV1beta1SpecAwsArgs']]:
        """
        AWS Secrets Manager configuration.
        """
        return pulumi.get(self, "aws")

    @aws.setter
    def aws(self, value: Optional[pulumi.Input['AppsSecretKeeperV1beta1SpecAwsArgs']]):
        pulumi.set(self, "aws", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Keeper description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)


class AppsSecretKeeperV1beta1SpecAwsArgsDict(TypedDict):
    region: pulumi.Input[_builtins.str]
    """
    AWS region.
    """
    assume_role: NotRequired[pulumi.Input['AppsSecretKeeperV1beta1SpecAwsAssumeRoleArgsDict']]
    """
    IAM role assumption configuration.
    """

@pulumi.input_type
class AppsSecretKeeperV1beta1SpecAwsArgs:
    def __init__(__self__, *,
                 region: pulumi.Input[_builtins.str],
                 assume_role: Optional[pulumi.Input['AppsSecretKeeperV1beta1SpecAwsAssumeRoleArgs']] = None):
        """
        :param pulumi.Input[_builtins.str] region: AWS region.
        :param pulumi.Input['AppsSecretKeeperV1beta1SpecAwsAssumeRoleArgs'] assume_role: IAM role assumption configuration.
        """
        pulumi.set(__self__, "region", region)
        if assume_role is not None:
            pulumi.set(__self__, "assume_role", assume_role)

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Input[_builtins.str]:
        """
        AWS region.
        """
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "region", value)

    @_builtins.property
    @pulumi.getter(name="assumeRole")
    def assume_role(self) -> Optional[pulumi.Input['AppsSecretKeeperV1beta1SpecAwsAssumeRoleArgs']]:
        """
        IAM role assumption configuration.
        """
        return pulumi.get(self, "assume_role")

    @assume_role.setter
    def assume_role(self, value: Optional[pulumi.Input['AppsSecretKeeperV1beta1SpecAwsAssumeRoleArgs']]):
        pulumi.set(self, "assume_role", value)


class AppsSecretKeeperV1beta1SpecAwsAssumeRoleArgsDict(TypedDict):
    assume_role_arn: NotRequired[pulumi.Input[_builtins.str]]
    """
    Assume role ARN.
    """
    external_id: NotRequired[pulumi.Input[_builtins.str]]
    """
    Assume role external ID.
    """

@pulumi.input_type
class AppsSecretKeeperV1beta1SpecAwsAssumeRoleArgs:
    def __init__(__self__, *,
                 assume_role_arn: Optional[pulumi.Input[_builtins.str]] = None,
                 external_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] assume_role_arn: Assume role ARN.
        :param pulumi.Input[_builtins.str] external_id: Assume role external ID.
        """
        if assume_role_arn is not None:
            pulumi.set(__self__, "assume_role_arn", assume_role_arn)
        if external_id is not None:
            pulumi.set(__self__, "external_id", external_id)

    @_builtins.property
    @pulumi.getter(name="assumeRoleArn")
    def assume_role_arn(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Assume role ARN.
        """
        return pulumi.get(self, "assume_role_arn")

    @assume_role_arn.setter
    def assume_role_arn(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "assume_role_arn", value)

    @_builtins.property
    @pulumi.getter(name="externalId")
    def external_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Assume role external ID.
        """
        return pulumi.get(self, "external_id")

    @external_id.setter
    def external_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "external_id", value)


class AppsSecretSecurevalueV1beta1MetadataArgsDict(TypedDict):
    uid: pulumi.Input[_builtins.str]
    """
    The unique identifier of the resource.
    """
    annotations: NotRequired[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]
    """
    Annotations of the resource.
    """
    folder_uid: NotRequired[pulumi.Input[_builtins.str]]
    """
    The UID of the folder to save the resource in.
    """
    url: NotRequired[pulumi.Input[_builtins.str]]
    """
    The full URL of the resource.
    """
    uuid: NotRequired[pulumi.Input[_builtins.str]]
    """
    The globally unique identifier of a resource, used by the API for tracking.
    """
    version: NotRequired[pulumi.Input[_builtins.str]]
    """
    The version of the resource.
    """

@pulumi.input_type
class AppsSecretSecurevalueV1beta1MetadataArgs:
    def __init__(__self__, *,
                 uid: pulumi.Input[_builtins.str],
                 annotations: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 folder_uid: Optional[pulumi.Input[_builtins.str]] = None,
                 url: Optional[pulumi.Input[_builtins.str]] = None,
                 uuid: Optional[pulumi.Input[_builtins.str]] = None,
                 version: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] uid: The unique identifier of the resource.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] annotations: Annotations of the resource.
        :param pulumi.Input[_builtins.str] folder_uid: The UID of the folder to save the resource in.
        :param pulumi.Input[_builtins.str] url: The full URL of the resource.
        :param pulumi.Input[_builtins.str] uuid: The globally unique identifier of a resource, used by the API for tracking.
        :param pulumi.Input[_builtins.str] version: The version of the resource.
        """
        pulumi.set(__self__, "uid", uid)
        if annotations is not None:
            pulumi.set(__self__, "annotations", annotations)
        if folder_uid is not None:
            pulumi.set(__self__, "folder_uid", folder_uid)
        if url is not None:
            pulumi.set(__self__, "url", url)
        if uuid is not None:
            pulumi.set(__self__, "uuid", uuid)
        if version is not None:
            pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter
    def uid(self) -> pulumi.Input[_builtins.str]:
        """
        The unique identifier of the resource.
        """
        return pulumi.get(self, "uid")

    @uid.setter
    def uid(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "uid", value)

    @_builtins.property
    @pulumi.getter
    def annotations(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Annotations of the resource.
        """
        return pulumi.get(self, "annotations")

    @annotations.setter
    def annotations(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "annotations", value)

    @_builtins.property
    @pulumi.getter(name="folderUid")
    def folder_uid(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The UID of the folder to save the resource in.
        """
        return pulumi.get(self, "folder_uid")

    @folder_uid.setter
    def folder_uid(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "folder_uid", value)

    @_builtins.property
    @pulumi.getter
    def url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The full URL of the resource.
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "url", value)

    @_builtins.property
    @pulumi.getter
    def uuid(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The globally unique identifier of a resource, used by the API for tracking.
        """
        return pulumi.get(self, "uuid")

    @uuid.setter
    def uuid(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "uuid", value)

    @_builtins.property
    @pulumi.getter
    def version(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The version of the resource.
        """
        return pulumi.get(self, "version")

    @version.setter
    def version(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "version", value)


class AppsSecretSecurevalueV1beta1OptionsArgsDict(TypedDict):
    overwrite: NotRequired[pulumi.Input[_builtins.bool]]
    """
    Set to true if you want to overwrite existing resource with newer version, same resource title in folder or same resource uid.
    """

@pulumi.input_type
class AppsSecretSecurevalueV1beta1OptionsArgs:
    def __init__(__self__, *,
                 overwrite: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        :param pulumi.Input[_builtins.bool] overwrite: Set to true if you want to overwrite existing resource with newer version, same resource title in folder or same resource uid.
        """
        if overwrite is not None:
            pulumi.set(__self__, "overwrite", overwrite)

    @_builtins.property
    @pulumi.getter
    def overwrite(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Set to true if you want to overwrite existing resource with newer version, same resource title in folder or same resource uid.
        """
        return pulumi.get(self, "overwrite")

    @overwrite.setter
    def overwrite(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "overwrite", value)


class AppsSecretSecurevalueV1beta1SpecArgsDict(TypedDict):
    decrypters: NotRequired[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]
    """
    List of decrypters allowed to read this secure value.
    """
    description: NotRequired[pulumi.Input[_builtins.str]]
    """
    Secure value description.
    """
    ref: NotRequired[pulumi.Input[_builtins.str]]
    """
    Reference to an existing secret managed by the keeper.
    """
    value: NotRequired[pulumi.Input[_builtins.str]]
    """
    **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
    Plaintext value to store. This value is write-only.
    """
    value_hash: NotRequired[pulumi.Input[_builtins.str]]
    """
    Hash of the stored plaintext value.
    """

@pulumi.input_type
class AppsSecretSecurevalueV1beta1SpecArgs:
    def __init__(__self__, *,
                 decrypters: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 ref: Optional[pulumi.Input[_builtins.str]] = None,
                 value: Optional[pulumi.Input[_builtins.str]] = None,
                 value_hash: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] decrypters: List of decrypters allowed to read this secure value.
        :param pulumi.Input[_builtins.str] description: Secure value description.
        :param pulumi.Input[_builtins.str] ref: Reference to an existing secret managed by the keeper.
        :param pulumi.Input[_builtins.str] value: **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
               Plaintext value to store. This value is write-only.
        :param pulumi.Input[_builtins.str] value_hash: Hash of the stored plaintext value.
        """
        if decrypters is not None:
            pulumi.set(__self__, "decrypters", decrypters)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if ref is not None:
            pulumi.set(__self__, "ref", ref)
        if value is not None:
            pulumi.set(__self__, "value", value)
        if value_hash is not None:
            pulumi.set(__self__, "value_hash", value_hash)

    @_builtins.property
    @pulumi.getter
    def decrypters(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of decrypters allowed to read this secure value.
        """
        return pulumi.get(self, "decrypters")

    @decrypters.setter
    def decrypters(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "decrypters", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Secure value description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def ref(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Reference to an existing secret managed by the keeper.
        """
        return pulumi.get(self, "ref")

    @ref.setter
    def ref(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "ref", value)

    @_builtins.property
    @pulumi.getter
    def value(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        Plaintext value to store. This value is write-only.
        """
        return pulumi.get(self, "value")

    @value.setter
    def value(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "value", value)

    @_builtins.property
    @pulumi.getter(name="valueHash")
    def value_hash(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Hash of the stored plaintext value.
        """
        return pulumi.get(self, "value_hash")

    @value_hash.setter
    def value_hash(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "value_hash", value)


