// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * Manages Grafana Alert Rules.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as grafana from "@pulumiverse/grafana";
 *
 * const alertruleFolder = new grafana.oss.Folder("alertrule_folder", {title: "Alert Rule Folder"});
 * const example = new grafana.alerting.AlertRuleV0Alpha1("example", {
 *     metadata: {
 *         uid: "example-alert-rule",
 *         folderUid: alertruleFolder.uid,
 *     },
 *     spec: {
 *         title: "Example Alert Rule",
 *         trigger: {
 *             interval: "1m",
 *         },
 *         paused: true,
 *         expressions: {
 *             A: {
 *                 model: {
 *                     datasource: {
 *                         type: "prometheus",
 *                         uid: "ds_uid",
 *                     },
 *                     editorMode: "code",
 *                     expr: "count(up{})",
 *                     instant: true,
 *                     intervalMs: 1000,
 *                     legendFormat: "__auto",
 *                     maxDataPoints: 43200,
 *                     range: false,
 *                     refId: "A",
 *                 },
 *                 datasourceUid: "ds_uid",
 *                 relativeTimeRange: {
 *                     from: "600s",
 *                     to: "0s",
 *                 },
 *                 queryType: "",
 *                 source: true,
 *             },
 *             B: {
 *                 model: {
 *                     conditions: [{
 *                         evaluator: {
 *                             params: [1],
 *                             type: "gt",
 *                         },
 *                         operator: {
 *                             type: "and",
 *                         },
 *                         query: {
 *                             params: ["C"],
 *                         },
 *                         reducer: {
 *                             params: [],
 *                             type: "last",
 *                         },
 *                         type: "query",
 *                     }],
 *                     datasource: {
 *                         type: "__expr__",
 *                         uid: "__expr__",
 *                     },
 *                     expression: "A",
 *                     intervalMs: 1000,
 *                     maxDataPoints: 43200,
 *                     refId: "C",
 *                     type: "threshold",
 *                 },
 *                 datasourceUid: "__expr__",
 *                 queryType: "",
 *                 source: false,
 *             },
 *         },
 *         "for": "5m",
 *         labels: {
 *             severity: "critical",
 *         },
 *         annotations: {
 *             runbook_url: "https://example.com",
 *         },
 *         noDataState: "KeepLast",
 *         execErrState: "KeepLast",
 *         missingSeriesEvalsToResolve: 5,
 *         notificationSettings: {
 *             contactPoint: "grafana-default-email",
 *         },
 *     },
 * });
 * ```
 */
export class AlertRuleV0Alpha1 extends pulumi.CustomResource {
    /**
     * Get an existing AlertRuleV0Alpha1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AlertRuleV0Alpha1State, opts?: pulumi.CustomResourceOptions): AlertRuleV0Alpha1 {
        return new AlertRuleV0Alpha1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'grafana:alerting/alertRuleV0Alpha1:AlertRuleV0Alpha1';

    /**
     * Returns true if the given object is an instance of AlertRuleV0Alpha1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AlertRuleV0Alpha1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AlertRuleV0Alpha1.__pulumiType;
    }

    /**
     * The metadata of the resource.
     */
    declare public readonly metadata: pulumi.Output<outputs.alerting.AlertRuleV0Alpha1Metadata | undefined>;
    /**
     * Options for applying the resource.
     */
    declare public readonly options: pulumi.Output<outputs.alerting.AlertRuleV0Alpha1Options | undefined>;
    /**
     * The spec of the resource.
     */
    declare public readonly spec: pulumi.Output<outputs.alerting.AlertRuleV0Alpha1Spec | undefined>;

    /**
     * Create a AlertRuleV0Alpha1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: AlertRuleV0Alpha1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AlertRuleV0Alpha1Args | AlertRuleV0Alpha1State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AlertRuleV0Alpha1State | undefined;
            resourceInputs["metadata"] = state?.metadata;
            resourceInputs["options"] = state?.options;
            resourceInputs["spec"] = state?.spec;
        } else {
            const args = argsOrState as AlertRuleV0Alpha1Args | undefined;
            resourceInputs["metadata"] = args?.metadata;
            resourceInputs["options"] = args?.options;
            resourceInputs["spec"] = args?.spec;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AlertRuleV0Alpha1.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AlertRuleV0Alpha1 resources.
 */
export interface AlertRuleV0Alpha1State {
    /**
     * The metadata of the resource.
     */
    metadata?: pulumi.Input<inputs.alerting.AlertRuleV0Alpha1Metadata>;
    /**
     * Options for applying the resource.
     */
    options?: pulumi.Input<inputs.alerting.AlertRuleV0Alpha1Options>;
    /**
     * The spec of the resource.
     */
    spec?: pulumi.Input<inputs.alerting.AlertRuleV0Alpha1Spec>;
}

/**
 * The set of arguments for constructing a AlertRuleV0Alpha1 resource.
 */
export interface AlertRuleV0Alpha1Args {
    /**
     * The metadata of the resource.
     */
    metadata?: pulumi.Input<inputs.alerting.AlertRuleV0Alpha1Metadata>;
    /**
     * Options for applying the resource.
     */
    options?: pulumi.Input<inputs.alerting.AlertRuleV0Alpha1Options>;
    /**
     * The spec of the resource.
     */
    spec?: pulumi.Input<inputs.alerting.AlertRuleV0Alpha1Spec>;
}
