// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Grafana.Outputs
{

    [OutputType]
    public sealed class AppsServicemodelComponentV1alpha1Spec
    {
        /// <summary>
        /// References to services this service depends on.
        /// </summary>
        public readonly ImmutableArray<Outputs.AppsServicemodelComponentV1alpha1SpecDependsOnRef> DependsOnRefs;
        /// <summary>
        /// Description of the service.
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// Additional key/value pairs used to match resources to the service: a resource matches when it has a label or tag with the same key and value. For example, an identifier with key `Namespace` and value `checkout-prod` matches alerts, SLOs and dashboards labeled or tagged `namespace=checkout-prod`. Maximum of 5. A `ServiceName` identifier equal to `metadata.uid` is implicit; add an explicit `ServiceName` when the telemetry value differs from the uid, for example because it contains characters the uid does not allow (such as uppercase letters, dots or underscores); the explicit value is matched in addition to the uid.
        /// </summary>
        public readonly ImmutableArray<Outputs.AppsServicemodelComponentV1alpha1SpecIdentifier> Identifiers;
        /// <summary>
        /// Links attached to the service (documentation, repository, etc.).
        /// </summary>
        public readonly ImmutableArray<Outputs.AppsServicemodelComponentV1alpha1SpecLink> Links;
        /// <summary>
        /// Reference to the team owning the service. Set `Name` to the Grafana team UID; `ApiVersion` and `Kind` default to a Grafana IAM team reference.
        /// </summary>
        public readonly Outputs.AppsServicemodelComponentV1alpha1SpecOwnerRef? OwnerRef;
        /// <summary>
        /// Display name of the service.
        /// </summary>
        public readonly string Title;
        /// <summary>
        /// Component type. Defaults to `Service`, the only type currently displayed by Service Center.
        /// </summary>
        public readonly string? Type;

        [OutputConstructor]
        private AppsServicemodelComponentV1alpha1Spec(
            ImmutableArray<Outputs.AppsServicemodelComponentV1alpha1SpecDependsOnRef> dependsOnRefs,

            string? description,

            ImmutableArray<Outputs.AppsServicemodelComponentV1alpha1SpecIdentifier> identifiers,

            ImmutableArray<Outputs.AppsServicemodelComponentV1alpha1SpecLink> links,

            Outputs.AppsServicemodelComponentV1alpha1SpecOwnerRef? ownerRef,

            string title,

            string? type)
        {
            DependsOnRefs = dependsOnRefs;
            Description = description;
            Identifiers = identifiers;
            Links = links;
            OwnerRef = ownerRef;
            Title = title;
            Type = type;
        }
    }
}
