// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Grafana.Oss.Inputs
{

    public sealed class SsoSettingsLdapSettingsConfigGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("servers", required: true)]
        private InputList<Inputs.SsoSettingsLdapSettingsConfigServerGetArgs>? _servers;

        /// <summary>
        /// The LDAP servers configuration.
        /// </summary>
        public InputList<Inputs.SsoSettingsLdapSettingsConfigServerGetArgs> Servers
        {
            get => _servers ?? (_servers = new InputList<Inputs.SsoSettingsLdapSettingsConfigServerGetArgs>());
            set => _servers = value;
        }

        public SsoSettingsLdapSettingsConfigGetArgs()
        {
        }
        public static new SsoSettingsLdapSettingsConfigGetArgs Empty => new SsoSettingsLdapSettingsConfigGetArgs();
    }
}
