# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

__all__ = [
    'CustomModelRulesRules',
    'CustomModelRulesRulesEntity',
    'CustomModelRulesRulesEntityDefinedBy',
    'LogConfigMatch',
    'ProfileConfigMatch',
    'PromRuleFileGroup',
    'PromRuleFileGroupRule',
    'StackDataset',
    'StackDatasetFilterGroup',
    'StackDatasetFilterGroupFilter',
    'ThresholdsHealthThreshold',
    'ThresholdsRequestThreshold',
    'ThresholdsResourceThreshold',
    'TraceConfigMatch',
]

@pulumi.output_type
class CustomModelRulesRules(dict):
    def __init__(__self__, *,
                 entities: Sequence['outputs.CustomModelRulesRulesEntity']):
        """
        :param Sequence['CustomModelRulesRulesEntityArgs'] entities: List of entities to define in the custom model rules.
        """
        pulumi.set(__self__, "entities", entities)

    @_builtins.property
    @pulumi.getter
    def entities(self) -> Sequence['outputs.CustomModelRulesRulesEntity']:
        """
        List of entities to define in the custom model rules.
        """
        return pulumi.get(self, "entities")


@pulumi.output_type
class CustomModelRulesRulesEntity(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "definedBies":
            suggest = "defined_bies"
        elif key == "enrichedBies":
            suggest = "enriched_bies"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in CustomModelRulesRulesEntity. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        CustomModelRulesRulesEntity.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        CustomModelRulesRulesEntity.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 defined_bies: Sequence['outputs.CustomModelRulesRulesEntityDefinedBy'],
                 name: _builtins.str,
                 type: _builtins.str,
                 disabled: Optional[_builtins.bool] = None,
                 enriched_bies: Optional[Sequence[_builtins.str]] = None,
                 lookup: Optional[Mapping[str, _builtins.str]] = None,
                 scope: Optional[Mapping[str, _builtins.str]] = None):
        """
        :param Sequence['CustomModelRulesRulesEntityDefinedByArgs'] defined_bies: List of queries that define this entity.
        :param _builtins.str name: The name of the entity.
        :param _builtins.str type: The type of the entity (e.g., Service, Pod, Namespace).
        :param _builtins.bool disabled: Whether this entity is disabled.
        :param Sequence[_builtins.str] enriched_bies: List of enrichment sources for the entity.
        :param Mapping[str, _builtins.str] lookup: Lookup mappings for the entity.
        :param Mapping[str, _builtins.str] scope: Scope labels for the entity.
        """
        pulumi.set(__self__, "defined_bies", defined_bies)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "type", type)
        if disabled is not None:
            pulumi.set(__self__, "disabled", disabled)
        if enriched_bies is not None:
            pulumi.set(__self__, "enriched_bies", enriched_bies)
        if lookup is not None:
            pulumi.set(__self__, "lookup", lookup)
        if scope is not None:
            pulumi.set(__self__, "scope", scope)

    @_builtins.property
    @pulumi.getter(name="definedBies")
    def defined_bies(self) -> Sequence['outputs.CustomModelRulesRulesEntityDefinedBy']:
        """
        List of queries that define this entity.
        """
        return pulumi.get(self, "defined_bies")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The name of the entity.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str:
        """
        The type of the entity (e.g., Service, Pod, Namespace).
        """
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter
    def disabled(self) -> Optional[_builtins.bool]:
        """
        Whether this entity is disabled.
        """
        return pulumi.get(self, "disabled")

    @_builtins.property
    @pulumi.getter(name="enrichedBies")
    def enriched_bies(self) -> Optional[Sequence[_builtins.str]]:
        """
        List of enrichment sources for the entity.
        """
        return pulumi.get(self, "enriched_bies")

    @_builtins.property
    @pulumi.getter
    def lookup(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Lookup mappings for the entity.
        """
        return pulumi.get(self, "lookup")

    @_builtins.property
    @pulumi.getter
    def scope(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Scope labels for the entity.
        """
        return pulumi.get(self, "scope")


@pulumi.output_type
class CustomModelRulesRulesEntityDefinedBy(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "labelValues":
            suggest = "label_values"
        elif key == "metricValue":
            suggest = "metric_value"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in CustomModelRulesRulesEntityDefinedBy. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        CustomModelRulesRulesEntityDefinedBy.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        CustomModelRulesRulesEntityDefinedBy.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 query: _builtins.str,
                 disabled: Optional[_builtins.bool] = None,
                 label_values: Optional[Mapping[str, _builtins.str]] = None,
                 literals: Optional[Mapping[str, _builtins.str]] = None,
                 metric_value: Optional[_builtins.str] = None):
        """
        :param _builtins.str query: The Prometheus query that defines this entity.
        :param _builtins.bool disabled: Whether this rule is disabled. When true, only the 'query' field is used to match an existing rule to disable; other fields are ignored.
        :param Mapping[str, _builtins.str] label_values: Label value mappings for the query.
        :param Mapping[str, _builtins.str] literals: Literal value mappings for the query.
        :param _builtins.str metric_value: Metric value for the query.
        """
        pulumi.set(__self__, "query", query)
        if disabled is not None:
            pulumi.set(__self__, "disabled", disabled)
        if label_values is not None:
            pulumi.set(__self__, "label_values", label_values)
        if literals is not None:
            pulumi.set(__self__, "literals", literals)
        if metric_value is not None:
            pulumi.set(__self__, "metric_value", metric_value)

    @_builtins.property
    @pulumi.getter
    def query(self) -> _builtins.str:
        """
        The Prometheus query that defines this entity.
        """
        return pulumi.get(self, "query")

    @_builtins.property
    @pulumi.getter
    def disabled(self) -> Optional[_builtins.bool]:
        """
        Whether this rule is disabled. When true, only the 'query' field is used to match an existing rule to disable; other fields are ignored.
        """
        return pulumi.get(self, "disabled")

    @_builtins.property
    @pulumi.getter(name="labelValues")
    def label_values(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Label value mappings for the query.
        """
        return pulumi.get(self, "label_values")

    @_builtins.property
    @pulumi.getter
    def literals(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Literal value mappings for the query.
        """
        return pulumi.get(self, "literals")

    @_builtins.property
    @pulumi.getter(name="metricValue")
    def metric_value(self) -> Optional[_builtins.str]:
        """
        Metric value for the query.
        """
        return pulumi.get(self, "metric_value")


@pulumi.output_type
class LogConfigMatch(dict):
    def __init__(__self__, *,
                 op: _builtins.str,
                 property: _builtins.str,
                 values: Sequence[_builtins.str]):
        """
        :param _builtins.str op: Operation to use for matching. One of: =, <>, <, >, <=, >=, IS NULL, IS NOT NULL, STARTS WITH, CONTAINS.
        :param _builtins.str property: Entity property to match.
        :param Sequence[_builtins.str] values: Values to match against.
        """
        pulumi.set(__self__, "op", op)
        pulumi.set(__self__, "property", property)
        pulumi.set(__self__, "values", values)

    @_builtins.property
    @pulumi.getter
    def op(self) -> _builtins.str:
        """
        Operation to use for matching. One of: =, <>, <, >, <=, >=, IS NULL, IS NOT NULL, STARTS WITH, CONTAINS.
        """
        return pulumi.get(self, "op")

    @_builtins.property
    @pulumi.getter
    def property(self) -> _builtins.str:
        """
        Entity property to match.
        """
        return pulumi.get(self, "property")

    @_builtins.property
    @pulumi.getter
    def values(self) -> Sequence[_builtins.str]:
        """
        Values to match against.
        """
        return pulumi.get(self, "values")


@pulumi.output_type
class ProfileConfigMatch(dict):
    def __init__(__self__, *,
                 op: _builtins.str,
                 property: _builtins.str,
                 values: Sequence[_builtins.str]):
        """
        :param _builtins.str op: Operation to use for matching. One of: =, <>, <, >, <=, >=, IS NULL, IS NOT NULL, STARTS WITH, CONTAINS.
        :param _builtins.str property: Entity property to match.
        :param Sequence[_builtins.str] values: Values to match against.
        """
        pulumi.set(__self__, "op", op)
        pulumi.set(__self__, "property", property)
        pulumi.set(__self__, "values", values)

    @_builtins.property
    @pulumi.getter
    def op(self) -> _builtins.str:
        """
        Operation to use for matching. One of: =, <>, <, >, <=, >=, IS NULL, IS NOT NULL, STARTS WITH, CONTAINS.
        """
        return pulumi.get(self, "op")

    @_builtins.property
    @pulumi.getter
    def property(self) -> _builtins.str:
        """
        Entity property to match.
        """
        return pulumi.get(self, "property")

    @_builtins.property
    @pulumi.getter
    def values(self) -> Sequence[_builtins.str]:
        """
        Values to match against.
        """
        return pulumi.get(self, "values")


@pulumi.output_type
class PromRuleFileGroup(dict):
    def __init__(__self__, *,
                 name: _builtins.str,
                 rules: Sequence['outputs.PromRuleFileGroupRule'],
                 interval: Optional[_builtins.str] = None):
        """
        :param _builtins.str name: The name of the rule group (e.g., 'latency_monitoring').
        :param Sequence['PromRuleFileGroupRuleArgs'] rules: List of Prometheus rules in this group.
        :param _builtins.str interval: Evaluation interval for this group (e.g., '30s', '1m'). If not specified, uses the global evaluation interval.
        """
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "rules", rules)
        if interval is not None:
            pulumi.set(__self__, "interval", interval)

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The name of the rule group (e.g., 'latency_monitoring').
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def rules(self) -> Sequence['outputs.PromRuleFileGroupRule']:
        """
        List of Prometheus rules in this group.
        """
        return pulumi.get(self, "rules")

    @_builtins.property
    @pulumi.getter
    def interval(self) -> Optional[_builtins.str]:
        """
        Evaluation interval for this group (e.g., '30s', '1m'). If not specified, uses the global evaluation interval.
        """
        return pulumi.get(self, "interval")


@pulumi.output_type
class PromRuleFileGroupRule(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "disableInGroups":
            suggest = "disable_in_groups"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in PromRuleFileGroupRule. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        PromRuleFileGroupRule.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        PromRuleFileGroupRule.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 expr: _builtins.str,
                 active: Optional[_builtins.bool] = None,
                 alert: Optional[_builtins.str] = None,
                 annotations: Optional[Mapping[str, _builtins.str]] = None,
                 disable_in_groups: Optional[Sequence[_builtins.str]] = None,
                 duration: Optional[_builtins.str] = None,
                 labels: Optional[Mapping[str, _builtins.str]] = None,
                 record: Optional[_builtins.str] = None):
        """
        :param _builtins.str expr: The PromQL expression to evaluate.
        :param _builtins.bool active: Whether this specific rule is active. This field is read-only and controlled by the API.
        :param _builtins.str alert: The name of the alert for alerting rules. Either 'record' or 'alert' must be specified, but not both.
        :param Mapping[str, _builtins.str] annotations: Annotations to add to alerts (e.g., summary, description).
        :param Sequence[_builtins.str] disable_in_groups: List of group names where this rule should be disabled. Useful for conditional rule enablement.
        :param _builtins.str duration: How long the condition must be true before firing the alert (e.g., '5m'). Only applicable for alerting rules. Maps to 'for' in Prometheus.
        :param Mapping[str, _builtins.str] labels: Labels to attach to the resulting time series or alert.
        :param _builtins.str record: The name of the time series to output for recording rules. Either 'record' or 'alert' must be specified, but not both.
        """
        pulumi.set(__self__, "expr", expr)
        if active is not None:
            pulumi.set(__self__, "active", active)
        if alert is not None:
            pulumi.set(__self__, "alert", alert)
        if annotations is not None:
            pulumi.set(__self__, "annotations", annotations)
        if disable_in_groups is not None:
            pulumi.set(__self__, "disable_in_groups", disable_in_groups)
        if duration is not None:
            pulumi.set(__self__, "duration", duration)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if record is not None:
            pulumi.set(__self__, "record", record)

    @_builtins.property
    @pulumi.getter
    def expr(self) -> _builtins.str:
        """
        The PromQL expression to evaluate.
        """
        return pulumi.get(self, "expr")

    @_builtins.property
    @pulumi.getter
    def active(self) -> Optional[_builtins.bool]:
        """
        Whether this specific rule is active. This field is read-only and controlled by the API.
        """
        return pulumi.get(self, "active")

    @_builtins.property
    @pulumi.getter
    def alert(self) -> Optional[_builtins.str]:
        """
        The name of the alert for alerting rules. Either 'record' or 'alert' must be specified, but not both.
        """
        return pulumi.get(self, "alert")

    @_builtins.property
    @pulumi.getter
    def annotations(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Annotations to add to alerts (e.g., summary, description).
        """
        return pulumi.get(self, "annotations")

    @_builtins.property
    @pulumi.getter(name="disableInGroups")
    def disable_in_groups(self) -> Optional[Sequence[_builtins.str]]:
        """
        List of group names where this rule should be disabled. Useful for conditional rule enablement.
        """
        return pulumi.get(self, "disable_in_groups")

    @_builtins.property
    @pulumi.getter
    def duration(self) -> Optional[_builtins.str]:
        """
        How long the condition must be true before firing the alert (e.g., '5m'). Only applicable for alerting rules. Maps to 'for' in Prometheus.
        """
        return pulumi.get(self, "duration")

    @_builtins.property
    @pulumi.getter
    def labels(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Labels to attach to the resulting time series or alert.
        """
        return pulumi.get(self, "labels")

    @_builtins.property
    @pulumi.getter
    def record(self) -> Optional[_builtins.str]:
        """
        The name of the time series to output for recording rules. Either 'record' or 'alert' must be specified, but not both.
        """
        return pulumi.get(self, "record")


@pulumi.output_type
class StackDataset(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "disabledVendors":
            suggest = "disabled_vendors"
        elif key == "filterGroups":
            suggest = "filter_groups"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in StackDataset. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        StackDataset.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        StackDataset.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 type: _builtins.str,
                 disabled_vendors: Optional[Sequence[_builtins.str]] = None,
                 filter_groups: Optional[Sequence['outputs.StackDatasetFilterGroup']] = None):
        """
        :param _builtins.str type: The dataset type. Available types: `kubernetes`, `otel` (App O11y), `prometheus`, `aws`. Note: `kubernetes` requires K8s Monitoring to be enabled, and `otel` requires Application Observability to be enabled on the stack.
        :param Sequence[_builtins.str] disabled_vendors: List of vendors to disable for this dataset.
        :param Sequence['StackDatasetFilterGroupArgs'] filter_groups: Filter groups for this dataset. Use when you need custom label mappings.
        """
        pulumi.set(__self__, "type", type)
        if disabled_vendors is not None:
            pulumi.set(__self__, "disabled_vendors", disabled_vendors)
        if filter_groups is not None:
            pulumi.set(__self__, "filter_groups", filter_groups)

    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str:
        """
        The dataset type. Available types: `kubernetes`, `otel` (App O11y), `prometheus`, `aws`. Note: `kubernetes` requires K8s Monitoring to be enabled, and `otel` requires Application Observability to be enabled on the stack.
        """
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter(name="disabledVendors")
    def disabled_vendors(self) -> Optional[Sequence[_builtins.str]]:
        """
        List of vendors to disable for this dataset.
        """
        return pulumi.get(self, "disabled_vendors")

    @_builtins.property
    @pulumi.getter(name="filterGroups")
    def filter_groups(self) -> Optional[Sequence['outputs.StackDatasetFilterGroup']]:
        """
        Filter groups for this dataset. Use when you need custom label mappings.
        """
        return pulumi.get(self, "filter_groups")


@pulumi.output_type
class StackDatasetFilterGroup(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "envLabel":
            suggest = "env_label"
        elif key == "envLabelValues":
            suggest = "env_label_values"
        elif key == "envName":
            suggest = "env_name"
        elif key == "siteLabel":
            suggest = "site_label"
        elif key == "siteLabelValues":
            suggest = "site_label_values"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in StackDatasetFilterGroup. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        StackDatasetFilterGroup.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        StackDatasetFilterGroup.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 env_label: Optional[_builtins.str] = None,
                 env_label_values: Optional[Sequence[_builtins.str]] = None,
                 env_name: Optional[_builtins.str] = None,
                 filters: Optional[Sequence['outputs.StackDatasetFilterGroupFilter']] = None,
                 site_label: Optional[_builtins.str] = None,
                 site_label_values: Optional[Sequence[_builtins.str]] = None):
        """
        :param _builtins.str env_label: The metric label name used for environment (e.g., `env`, `environment`, `deployment_environment`). Defaults to standard labels if not set.
        :param Sequence[_builtins.str] env_label_values: Specific values of the environment label to match.
        :param _builtins.str env_name: A friendly name for the environment.
        :param Sequence['StackDatasetFilterGroupFilterArgs'] filters: Additional metric filters.
        :param _builtins.str site_label: The metric label name used for site/cluster.
        :param Sequence[_builtins.str] site_label_values: Specific values of the site label to match.
        """
        if env_label is not None:
            pulumi.set(__self__, "env_label", env_label)
        if env_label_values is not None:
            pulumi.set(__self__, "env_label_values", env_label_values)
        if env_name is not None:
            pulumi.set(__self__, "env_name", env_name)
        if filters is not None:
            pulumi.set(__self__, "filters", filters)
        if site_label is not None:
            pulumi.set(__self__, "site_label", site_label)
        if site_label_values is not None:
            pulumi.set(__self__, "site_label_values", site_label_values)

    @_builtins.property
    @pulumi.getter(name="envLabel")
    def env_label(self) -> Optional[_builtins.str]:
        """
        The metric label name used for environment (e.g., `env`, `environment`, `deployment_environment`). Defaults to standard labels if not set.
        """
        return pulumi.get(self, "env_label")

    @_builtins.property
    @pulumi.getter(name="envLabelValues")
    def env_label_values(self) -> Optional[Sequence[_builtins.str]]:
        """
        Specific values of the environment label to match.
        """
        return pulumi.get(self, "env_label_values")

    @_builtins.property
    @pulumi.getter(name="envName")
    def env_name(self) -> Optional[_builtins.str]:
        """
        A friendly name for the environment.
        """
        return pulumi.get(self, "env_name")

    @_builtins.property
    @pulumi.getter
    def filters(self) -> Optional[Sequence['outputs.StackDatasetFilterGroupFilter']]:
        """
        Additional metric filters.
        """
        return pulumi.get(self, "filters")

    @_builtins.property
    @pulumi.getter(name="siteLabel")
    def site_label(self) -> Optional[_builtins.str]:
        """
        The metric label name used for site/cluster.
        """
        return pulumi.get(self, "site_label")

    @_builtins.property
    @pulumi.getter(name="siteLabelValues")
    def site_label_values(self) -> Optional[Sequence[_builtins.str]]:
        """
        Specific values of the site label to match.
        """
        return pulumi.get(self, "site_label_values")


@pulumi.output_type
class StackDatasetFilterGroupFilter(dict):
    def __init__(__self__, *,
                 name: _builtins.str,
                 operator: _builtins.str,
                 values: Sequence[_builtins.str]):
        """
        :param _builtins.str name: The label name to filter on.
        :param _builtins.str operator: The filter operator (e.g., `=`, `!=`, `=~`, `!~`).
        :param Sequence[_builtins.str] values: The values to match.
        """
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "operator", operator)
        pulumi.set(__self__, "values", values)

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The label name to filter on.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def operator(self) -> _builtins.str:
        """
        The filter operator (e.g., `=`, `!=`, `=~`, `!~`).
        """
        return pulumi.get(self, "operator")

    @_builtins.property
    @pulumi.getter
    def values(self) -> Sequence[_builtins.str]:
        """
        The values to match.
        """
        return pulumi.get(self, "values")


@pulumi.output_type
class ThresholdsHealthThreshold(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "assertionName":
            suggest = "assertion_name"
        elif key == "entityType":
            suggest = "entity_type"
        elif key == "alertCategory":
            suggest = "alert_category"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ThresholdsHealthThreshold. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ThresholdsHealthThreshold.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ThresholdsHealthThreshold.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 assertion_name: _builtins.str,
                 entity_type: _builtins.str,
                 expression: _builtins.str,
                 alert_category: Optional[_builtins.str] = None):
        """
        :param _builtins.str assertion_name: Assertion name.
        :param _builtins.str entity_type: Entity type for the health threshold (e.g., Service, Pod, Namespace, Volume).
        :param _builtins.str expression: Prometheus expression.
        :param _builtins.str alert_category: Optional alert category label for the health threshold.
        """
        pulumi.set(__self__, "assertion_name", assertion_name)
        pulumi.set(__self__, "entity_type", entity_type)
        pulumi.set(__self__, "expression", expression)
        if alert_category is not None:
            pulumi.set(__self__, "alert_category", alert_category)

    @_builtins.property
    @pulumi.getter(name="assertionName")
    def assertion_name(self) -> _builtins.str:
        """
        Assertion name.
        """
        return pulumi.get(self, "assertion_name")

    @_builtins.property
    @pulumi.getter(name="entityType")
    def entity_type(self) -> _builtins.str:
        """
        Entity type for the health threshold (e.g., Service, Pod, Namespace, Volume).
        """
        return pulumi.get(self, "entity_type")

    @_builtins.property
    @pulumi.getter
    def expression(self) -> _builtins.str:
        """
        Prometheus expression.
        """
        return pulumi.get(self, "expression")

    @_builtins.property
    @pulumi.getter(name="alertCategory")
    def alert_category(self) -> Optional[_builtins.str]:
        """
        Optional alert category label for the health threshold.
        """
        return pulumi.get(self, "alert_category")


@pulumi.output_type
class ThresholdsRequestThreshold(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "assertionName":
            suggest = "assertion_name"
        elif key == "entityName":
            suggest = "entity_name"
        elif key == "requestContext":
            suggest = "request_context"
        elif key == "requestType":
            suggest = "request_type"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ThresholdsRequestThreshold. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ThresholdsRequestThreshold.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ThresholdsRequestThreshold.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 assertion_name: _builtins.str,
                 entity_name: _builtins.str,
                 request_context: _builtins.str,
                 request_type: _builtins.str,
                 value: _builtins.float):
        """
        :param _builtins.str assertion_name: Assertion name (e.g., RequestRateAnomaly, ErrorRatioBreach).
        :param _builtins.str entity_name: Entity name the threshold applies to.
        :param _builtins.str request_context: Request context (e.g., path or context identifier).
        :param _builtins.str request_type: Request type (e.g., inbound/outbound).
        :param _builtins.float value: Threshold value.
        """
        pulumi.set(__self__, "assertion_name", assertion_name)
        pulumi.set(__self__, "entity_name", entity_name)
        pulumi.set(__self__, "request_context", request_context)
        pulumi.set(__self__, "request_type", request_type)
        pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter(name="assertionName")
    def assertion_name(self) -> _builtins.str:
        """
        Assertion name (e.g., RequestRateAnomaly, ErrorRatioBreach).
        """
        return pulumi.get(self, "assertion_name")

    @_builtins.property
    @pulumi.getter(name="entityName")
    def entity_name(self) -> _builtins.str:
        """
        Entity name the threshold applies to.
        """
        return pulumi.get(self, "entity_name")

    @_builtins.property
    @pulumi.getter(name="requestContext")
    def request_context(self) -> _builtins.str:
        """
        Request context (e.g., path or context identifier).
        """
        return pulumi.get(self, "request_context")

    @_builtins.property
    @pulumi.getter(name="requestType")
    def request_type(self) -> _builtins.str:
        """
        Request type (e.g., inbound/outbound).
        """
        return pulumi.get(self, "request_type")

    @_builtins.property
    @pulumi.getter
    def value(self) -> _builtins.float:
        """
        Threshold value.
        """
        return pulumi.get(self, "value")


@pulumi.output_type
class ThresholdsResourceThreshold(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "assertionName":
            suggest = "assertion_name"
        elif key == "containerName":
            suggest = "container_name"
        elif key == "resourceType":
            suggest = "resource_type"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ThresholdsResourceThreshold. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ThresholdsResourceThreshold.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ThresholdsResourceThreshold.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 assertion_name: _builtins.str,
                 container_name: _builtins.str,
                 resource_type: _builtins.str,
                 severity: _builtins.str,
                 source: _builtins.str,
                 value: _builtins.float):
        """
        :param _builtins.str assertion_name: Assertion name (e.g., Saturation, ResourceRateBreach).
        :param _builtins.str container_name: Container name.
        :param _builtins.str resource_type: Resource type (e.g., container/pod/node).
        :param _builtins.str severity: Severity (warning or critical).
        :param _builtins.str source: Data source for the threshold (e.g., metrics/logs).
        :param _builtins.float value: Threshold value.
        """
        pulumi.set(__self__, "assertion_name", assertion_name)
        pulumi.set(__self__, "container_name", container_name)
        pulumi.set(__self__, "resource_type", resource_type)
        pulumi.set(__self__, "severity", severity)
        pulumi.set(__self__, "source", source)
        pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter(name="assertionName")
    def assertion_name(self) -> _builtins.str:
        """
        Assertion name (e.g., Saturation, ResourceRateBreach).
        """
        return pulumi.get(self, "assertion_name")

    @_builtins.property
    @pulumi.getter(name="containerName")
    def container_name(self) -> _builtins.str:
        """
        Container name.
        """
        return pulumi.get(self, "container_name")

    @_builtins.property
    @pulumi.getter(name="resourceType")
    def resource_type(self) -> _builtins.str:
        """
        Resource type (e.g., container/pod/node).
        """
        return pulumi.get(self, "resource_type")

    @_builtins.property
    @pulumi.getter
    def severity(self) -> _builtins.str:
        """
        Severity (warning or critical).
        """
        return pulumi.get(self, "severity")

    @_builtins.property
    @pulumi.getter
    def source(self) -> _builtins.str:
        """
        Data source for the threshold (e.g., metrics/logs).
        """
        return pulumi.get(self, "source")

    @_builtins.property
    @pulumi.getter
    def value(self) -> _builtins.float:
        """
        Threshold value.
        """
        return pulumi.get(self, "value")


@pulumi.output_type
class TraceConfigMatch(dict):
    def __init__(__self__, *,
                 op: _builtins.str,
                 property: _builtins.str,
                 values: Sequence[_builtins.str]):
        """
        :param _builtins.str op: Operation to use for matching. One of: =, <>, <, >, <=, >=, IS NULL, IS NOT NULL, STARTS WITH, CONTAINS.
        :param _builtins.str property: Entity property to match.
        :param Sequence[_builtins.str] values: Values to match against.
        """
        pulumi.set(__self__, "op", op)
        pulumi.set(__self__, "property", property)
        pulumi.set(__self__, "values", values)

    @_builtins.property
    @pulumi.getter
    def op(self) -> _builtins.str:
        """
        Operation to use for matching. One of: =, <>, <, >, <=, >=, IS NULL, IS NOT NULL, STARTS WITH, CONTAINS.
        """
        return pulumi.get(self, "op")

    @_builtins.property
    @pulumi.getter
    def property(self) -> _builtins.str:
        """
        Entity property to match.
        """
        return pulumi.get(self, "property")

    @_builtins.property
    @pulumi.getter
    def values(self) -> Sequence[_builtins.str]:
        """
        Values to match against.
        """
        return pulumi.get(self, "values")


