# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = ['RuleActionArgs', 'RuleAction']

@pulumi.input_type
class RuleActionArgs:
    def __init__(__self__, *,
                 collection_ids: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]],
                 condition: pulumi.Input[_builtins.str],
                 rule_id: pulumi.Input[_builtins.str],
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        The set of arguments for constructing a RuleAction resource.

        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] collection_ids: IDs of the collections that matching conversations are added to. Must be non-empty.
        :param pulumi.Input[_builtins.str] condition: Aggregate verdict that triggers the action. One of `all_evaluators_pass`, `all_evaluators_fail`.
        :param pulumi.Input[_builtins.str] rule_id: ID of the evaluation rule this action is attached to. Changing this forces a new resource.
        :param pulumi.Input[_builtins.bool] enabled: Whether the action is enabled. Defaults to `true`.
        """
        pulumi.set(__self__, "collection_ids", collection_ids)
        pulumi.set(__self__, "condition", condition)
        pulumi.set(__self__, "rule_id", rule_id)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)

    @_builtins.property
    @pulumi.getter(name="collectionIds")
    def collection_ids(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]:
        """
        IDs of the collections that matching conversations are added to. Must be non-empty.
        """
        return pulumi.get(self, "collection_ids")

    @collection_ids.setter
    def collection_ids(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "collection_ids", value)

    @_builtins.property
    @pulumi.getter
    def condition(self) -> pulumi.Input[_builtins.str]:
        """
        Aggregate verdict that triggers the action. One of `all_evaluators_pass`, `all_evaluators_fail`.
        """
        return pulumi.get(self, "condition")

    @condition.setter
    def condition(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "condition", value)

    @_builtins.property
    @pulumi.getter(name="ruleId")
    def rule_id(self) -> pulumi.Input[_builtins.str]:
        """
        ID of the evaluation rule this action is attached to. Changing this forces a new resource.
        """
        return pulumi.get(self, "rule_id")

    @rule_id.setter
    def rule_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "rule_id", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether the action is enabled. Defaults to `true`.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "enabled", value)


@pulumi.input_type
class _RuleActionState:
    def __init__(__self__, *,
                 collection_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 condition: Optional[pulumi.Input[_builtins.str]] = None,
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 rule_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering RuleAction resources.

        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] collection_ids: IDs of the collections that matching conversations are added to. Must be non-empty.
        :param pulumi.Input[_builtins.str] condition: Aggregate verdict that triggers the action. One of `all_evaluators_pass`, `all_evaluators_fail`.
        :param pulumi.Input[_builtins.bool] enabled: Whether the action is enabled. Defaults to `true`.
        :param pulumi.Input[_builtins.str] rule_id: ID of the evaluation rule this action is attached to. Changing this forces a new resource.
        """
        if collection_ids is not None:
            pulumi.set(__self__, "collection_ids", collection_ids)
        if condition is not None:
            pulumi.set(__self__, "condition", condition)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if rule_id is not None:
            pulumi.set(__self__, "rule_id", rule_id)

    @_builtins.property
    @pulumi.getter(name="collectionIds")
    def collection_ids(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        IDs of the collections that matching conversations are added to. Must be non-empty.
        """
        return pulumi.get(self, "collection_ids")

    @collection_ids.setter
    def collection_ids(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "collection_ids", value)

    @_builtins.property
    @pulumi.getter
    def condition(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Aggregate verdict that triggers the action. One of `all_evaluators_pass`, `all_evaluators_fail`.
        """
        return pulumi.get(self, "condition")

    @condition.setter
    def condition(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "condition", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether the action is enabled. Defaults to `true`.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter(name="ruleId")
    def rule_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        ID of the evaluation rule this action is attached to. Changing this forces a new resource.
        """
        return pulumi.get(self, "rule_id")

    @rule_id.setter
    def rule_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "rule_id", value)


@pulumi.type_token("grafana:agento11y/ruleAction:RuleAction")
class RuleAction(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 collection_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 condition: Optional[pulumi.Input[_builtins.str]] = None,
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 rule_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Manages an action attached to a Grafana Agent Observability evaluation rule. When the rule's aggregate verdict matches the configured condition, matching conversations are added to one or more collections.

        Requires a Grafana instance with the `grafana-agento11y-app` plugin installed.

        ## Example Usage

        ```python
        import pulumi
        import json
        import pulumiverse_grafana as grafana

        example = grafana.agento11y.Evaluator("example",
            evaluator_id="no_secrets",
            version="1",
            kind="regex",
            config=json.dumps({
                "pattern": "(?i)(api[_-]?key|password|secret)",
            }),
            output_keys=json.dumps([{
                "key": "clean",
                "type": "bool",
            }]))
        example_evaluation_rule = grafana.agento11y.EvaluationRule("example",
            rule_id="score_user_turns",
            selector="user_visible_turn",
            sample_rate=0.1,
            evaluator_ids=[example.evaluator_id])
        # Adds conversations to a collection when every evaluator on the rule fails.
        # The referenced collection must already exist in Agent Observability.
        example_rule_action = grafana.agento11y.RuleAction("example",
            rule_id=example_evaluation_rule.rule_id,
            condition="all_evaluators_fail",
            collection_ids=["failed-evaluations"])
        ```

        ## Import

        ```sh
        terraform import grafana_agento11y_rule_action.name "{{ rule_id }}:{{ action_id }}"
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] collection_ids: IDs of the collections that matching conversations are added to. Must be non-empty.
        :param pulumi.Input[_builtins.str] condition: Aggregate verdict that triggers the action. One of `all_evaluators_pass`, `all_evaluators_fail`.
        :param pulumi.Input[_builtins.bool] enabled: Whether the action is enabled. Defaults to `true`.
        :param pulumi.Input[_builtins.str] rule_id: ID of the evaluation rule this action is attached to. Changing this forces a new resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: RuleActionArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages an action attached to a Grafana Agent Observability evaluation rule. When the rule's aggregate verdict matches the configured condition, matching conversations are added to one or more collections.

        Requires a Grafana instance with the `grafana-agento11y-app` plugin installed.

        ## Example Usage

        ```python
        import pulumi
        import json
        import pulumiverse_grafana as grafana

        example = grafana.agento11y.Evaluator("example",
            evaluator_id="no_secrets",
            version="1",
            kind="regex",
            config=json.dumps({
                "pattern": "(?i)(api[_-]?key|password|secret)",
            }),
            output_keys=json.dumps([{
                "key": "clean",
                "type": "bool",
            }]))
        example_evaluation_rule = grafana.agento11y.EvaluationRule("example",
            rule_id="score_user_turns",
            selector="user_visible_turn",
            sample_rate=0.1,
            evaluator_ids=[example.evaluator_id])
        # Adds conversations to a collection when every evaluator on the rule fails.
        # The referenced collection must already exist in Agent Observability.
        example_rule_action = grafana.agento11y.RuleAction("example",
            rule_id=example_evaluation_rule.rule_id,
            condition="all_evaluators_fail",
            collection_ids=["failed-evaluations"])
        ```

        ## Import

        ```sh
        terraform import grafana_agento11y_rule_action.name "{{ rule_id }}:{{ action_id }}"
        ```


        :param str resource_name: The name of the resource.
        :param RuleActionArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(RuleActionArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 collection_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 condition: Optional[pulumi.Input[_builtins.str]] = None,
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 rule_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = RuleActionArgs.__new__(RuleActionArgs)

            if collection_ids is None and not opts.urn:
                raise TypeError("Missing required property 'collection_ids'")
            __props__.__dict__["collection_ids"] = collection_ids
            if condition is None and not opts.urn:
                raise TypeError("Missing required property 'condition'")
            __props__.__dict__["condition"] = condition
            __props__.__dict__["enabled"] = enabled
            if rule_id is None and not opts.urn:
                raise TypeError("Missing required property 'rule_id'")
            __props__.__dict__["rule_id"] = rule_id
        super(RuleAction, __self__).__init__(
            'grafana:agento11y/ruleAction:RuleAction',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            collection_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            condition: Optional[pulumi.Input[_builtins.str]] = None,
            enabled: Optional[pulumi.Input[_builtins.bool]] = None,
            rule_id: Optional[pulumi.Input[_builtins.str]] = None) -> 'RuleAction':
        """
        Get an existing RuleAction resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] collection_ids: IDs of the collections that matching conversations are added to. Must be non-empty.
        :param pulumi.Input[_builtins.str] condition: Aggregate verdict that triggers the action. One of `all_evaluators_pass`, `all_evaluators_fail`.
        :param pulumi.Input[_builtins.bool] enabled: Whether the action is enabled. Defaults to `true`.
        :param pulumi.Input[_builtins.str] rule_id: ID of the evaluation rule this action is attached to. Changing this forces a new resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _RuleActionState.__new__(_RuleActionState)

        __props__.__dict__["collection_ids"] = collection_ids
        __props__.__dict__["condition"] = condition
        __props__.__dict__["enabled"] = enabled
        __props__.__dict__["rule_id"] = rule_id
        return RuleAction(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="collectionIds")
    def collection_ids(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        IDs of the collections that matching conversations are added to. Must be non-empty.
        """
        return pulumi.get(self, "collection_ids")

    @_builtins.property
    @pulumi.getter
    def condition(self) -> pulumi.Output[_builtins.str]:
        """
        Aggregate verdict that triggers the action. One of `all_evaluators_pass`, `all_evaluators_fail`.
        """
        return pulumi.get(self, "condition")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the action is enabled. Defaults to `true`.
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter(name="ruleId")
    def rule_id(self) -> pulumi.Output[_builtins.str]:
        """
        ID of the evaluation rule this action is attached to. Changing this forces a new resource.
        """
        return pulumi.get(self, "rule_id")

