// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Grafana.Alerting.Inputs
{

    public sealed class AlertEnrichmentSpecStepConditionalThenGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("steps")]
        private InputList<Inputs.AlertEnrichmentSpecStepConditionalThenStepGetArgs>? _steps;
        public InputList<Inputs.AlertEnrichmentSpecStepConditionalThenStepGetArgs> Steps
        {
            get => _steps ?? (_steps = new InputList<Inputs.AlertEnrichmentSpecStepConditionalThenStepGetArgs>());
            set => _steps = value;
        }

        public AlertEnrichmentSpecStepConditionalThenGetArgs()
        {
        }
        public static new AlertEnrichmentSpecStepConditionalThenGetArgs Empty => new AlertEnrichmentSpecStepConditionalThenGetArgs();
    }
}
