// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Grafana.Alerting.Inputs
{

    public sealed class ContactPointWebhookHttpConfigOauth2ProxyConfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Comma-separated list of addresses that should not use a proxy.
        /// </summary>
        [Input("noProxy")]
        public Input<string>? NoProxy { get; set; }

        [Input("proxyConnectHeader")]
        private InputMap<string>? _proxyConnectHeader;

        /// <summary>
        /// Optional headers to send to proxies during CONNECT requests.
        /// </summary>
        public InputMap<string> ProxyConnectHeader
        {
            get => _proxyConnectHeader ?? (_proxyConnectHeader = new InputMap<string>());
            set => _proxyConnectHeader = value;
        }

        /// <summary>
        /// Use environment HTTP*PROXY, HTTPS*PROXY and NO_PROXY to determine proxies. Defaults to `False`.
        /// </summary>
        [Input("proxyFromEnvironment")]
        public Input<bool>? ProxyFromEnvironment { get; set; }

        /// <summary>
        /// HTTP proxy server to use to connect to the targets.
        /// </summary>
        [Input("proxyUrl")]
        public Input<string>? ProxyUrl { get; set; }

        public ContactPointWebhookHttpConfigOauth2ProxyConfigArgs()
        {
        }
        public static new ContactPointWebhookHttpConfigOauth2ProxyConfigArgs Empty => new ContactPointWebhookHttpConfigOauth2ProxyConfigArgs();
    }
}
