// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Grafana.Inputs
{

    public sealed class CloudAccessPolicyConditionArgs : global::Pulumi.ResourceArgs
    {
        [Input("allowedSubnets", required: true)]
        private InputList<string>? _allowedSubnets;

        /// <summary>
        /// Conditions that apply to the access policy,such as IP Allow lists.
        /// </summary>
        public InputList<string> AllowedSubnets
        {
            get => _allowedSubnets ?? (_allowedSubnets = new InputList<string>());
            set => _allowedSubnets = value;
        }

        public CloudAccessPolicyConditionArgs()
        {
        }
        public static new CloudAccessPolicyConditionArgs Empty => new CloudAccessPolicyConditionArgs();
    }
}
